feat: 회원탈퇴 DELETE api 구현
mocacong/Mocacong-Backend pull request #10
Opened 2023-03-26 13:36 UTC by Ji-soo708

## 개요
- JWT 토큰을 활용한 회원탈퇴 기능 구현 및 회원 탈퇴 테스트 코드 작성했습니다.

## 작업사항
- JWT 토큰 기반 회원탈퇴 기능을 구현했습니다.
- 기존에 존재했던 `delete()` 메서드를 수정하면서 문제가 생긴 기존 회원 탈퇴 테스트들에 대해서도 수정했습니다.
- 회원 탈퇴 인수 테스트 코드를 작성했습니다.

## 주의사항
- `deleteById` API를 만들어야 할 지 아직 결정하지 못했기에 merge 후에도 branch를 삭제하지 말아주세요
- 누락된 테스트 코드가 있는지 확인해주세요
- 잘못된 테스트 코드가 있는지 확인해주세요
- 내용에 오타가 있는지 확인해주세요

2023-03-26 13:43 UTC, Ji-soo708 reviewed
탈퇴 로직을 제대로 작성한 건지 잘 모르겠어서 코멘트 보시고 리뷰 남겨주시면 감사합니다!😊

2023-03-26 13:43 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/MemberController.java
> +    }
토큰을 얻고 사용자 인증을 한 후에 회원 탈퇴를 시켜야 한다고 생각해 JWT 토큰에서 사용자의 이메일 주소를 얻고 회원 탈퇴를 처리했습니다.
이 방법이 아닌 다른 방법으로 구현해야 한다면 알려주시면 수정하겠습니다!

2023-03-26 13:43 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/MemberService.java
> +    public void delete(@LoginUserEmail String email){
`@LoginUserEmail` 을 통해 로그인한 사용자의 이메일 주소를 대상으로 탈퇴 진행합니다.

2023-03-26 13:43 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/MemberServiceTest.java
탈퇴에 대한 예외 테스트가 이미 작성되어 있는 거로 충분하다 생각하여 기존 탈퇴 테스트 코드를 수정만 했습니다. 추가될 테스트 코드가 있다면 바로 추가하겠습니다!

2023-03-26 15:03 UTC, kth990303 requested changes
수고하셨습니다. 인증 관련된 부분때문에 RC로 남겼습니다 :)

2023-03-26 15:03 UTC, kth990303 commented on src/main/java/mocacong/server/controller/MemberController.java
> +        return ResponseEntity.ok("회원 탈퇴를 정상적으로 처리했습니다");
dto를 담아주지 않고 String으로 담는 것은 json형태가 아니기 때문에 rest api 통신에 적절치 않다고 생각됩니다. 아래와 같은 형식은 어떤가요?
```suggestion
        return ResponseEntity.ok().build();
```

2023-03-26 15:03 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +    public void delete(@LoginUserEmail String email){
여기서는 `String email`을 받는 것이 적절해보입니다~

2023-03-26 15:03 UTC, kth990303 commented on src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
> +                .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
```suggestion
                .as(TokenResponse.class)
                .getToken();

        RestAssured.given().log().all()
                .auth().oauth2(token)
```

2023-03-26 15:04 UTC, kth990303 commented on src/main/java/mocacong/server/controller/MemberController.java
> +    public ResponseEntity<String> delete(@RequestHeader("Authorization") String authorizationHeader) {
```suggestion
    public ResponseEntity<String> delete(@LoginUserEmail String email) {
```

2023-03-26 15:10 UTC, kth990303 commented on src/main/java/mocacong/server/controller/MemberController.java
> +    public ResponseEntity<String> delete(@RequestHeader("Authorization") String authorizationHeader) {
`@SecurityRequirement(name = "JWT")` 어노테이션이 있어야 swagger에서 인증 없이 해당 api를 쏠 때 에러를 띄워줍니다.

```suggestion
    @Operation(summary = "회원탈퇴")
    @SecurityRequirement(name = "JWT")
    @DeleteMapping
    public ResponseEntity<String> delete(@RequestHeader("Authorization") String authorizationHeader) {
```

2023-03-27 09:54 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/MemberController.java
> +    }
JWT 토큰을 따로 확인해줘야 하는 줄 알았는데 `@LoginUserEmail` 에서도 그 역할을 해주네요! 그 부분 반영해서 수정하겠습니다. 감사합니다!

2023-03-27 09:58 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/MemberController.java
> +        return ResponseEntity.ok("회원 탈퇴를 정상적으로 처리했습니다");
저도 저 부분이 거슬렸는데 해결책 알려주셔서 감사합니다! Void로 수정했습니다. 👍

2023-03-27 10:26 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/MemberController.java
> +    public ResponseEntity<String> delete(@RequestHeader("Authorization") String authorizationHeader) {
알려주셔서 감사합니다!

2023-03-27 10:26 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/MemberController.java
> +    public ResponseEntity<String> delete(@RequestHeader("Authorization") String authorizationHeader) {
참고해서 수정했습니다. 감사합니다~

2023-03-27 14:43 UTC, kth990303 commented on src/main/java/mocacong/server/config/AuthConfig.java
> +    }
`AuthenticationPrincipalArgumentResolver`를 webConfigurer에 등록해주었습니다.

2023-03-27 14:45 UTC, kth990303 approved these changes
잘 반영된 것 같아서 approve 했고, DM으로 얘기했다시피 제가 추가적인 작업을 좀 했어요.
확인해보시고 로컬에서 직접 실행해서 swagger로 회원탈퇴까지 잘 되는지 확인 후 머지해주세요!

2023-03-27 14:45 UTC, kth990303 commented on src/main/java/mocacong/server/config/AuthConfig.java
> +    }
`AuthenticationPrincipalArgumentResolver`를 WebMvcConfigurer에 등록해주었습니다.

2023-03-28 01:26 UTC, Ji-soo708 commented
제가 놓친 부분이랑 동작 잘 되는 거까지 확인하였습니다! 도와주셔서 감사합니다😊

2023-03-28 01:27 UTC, merged