fix: 카페 이미지 조회 GET API 로직 최근 순으로 정렬하도록 수정
mocacong/Mocacong-Backend pull request #105
Opened 2023-06-09 03:01 UTC by Ji-soo708

## 개요
- 기존 카페 이미지 조회 기능에서는 카페 이미지들을 카페 이미지 id 기준 오름차순으로 정렬하여 반환했습니다. 하지만 프론트의 요청으로 카페 이미지를 조회할 시, 먼저 자신이 올린 이미지를 최근 순으로 정렬하고 타인이 올린 이미지를 최근 순으로 정렬하여 반환하도록 수정했습니다.

## 작업사항
- 카페 이미지 조회 로직을 자신이 올린 사진부터 최근 순으로 정렬하도록 수정
- 카페 이미지 조회할 시, 최근 순으로 정렬이 되는지 검증하는 테스트 코드 추가
- 카페 이미지 조회 로직 수정에 따른 기존 카페 이미지 관련 테스트 코드 수정

## 주의사항
- 스웨거로 해당 기능이 정상적으로 동작되는지 확인해주세요
- 더 나은 로직이 있다면 추천해주세요

2023-06-09 03:06 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        int startIndex = page * count;
기존에 사용하던 `Slice` 을 통해 페이지네이션을 하고 싶었으나 그러려면 정렬된 리스트에서 `Slice` 를 통해 페이지네이션을 해야합니다. 하지만 리스트를 `Slice` 로 변환하는 것은 불가능하다 생각하여 직접 slice 하여 페이지네이션하는 식으로 변경했습니다. 혹시 더 좋은 방법이 있다면 코멘트 남겨주세요.

2023-06-09 03:06 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +                () -> assertThat(actual.getCafeImages().get(4).getImageUrl()).endsWith("test_img.jpg"),
카페 이미지 조회 로직 변경으로 해당 검증 코드를 변경했습니다.

2023-06-09 09:03 UTC, kth990303 requested changes
쿼리에서 `order by`를 이용하면 좋지 않을까 싶어서 리뷰 남겨봅니다

2023-06-10 04:48 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +                .thenComparing(CafeImageResponse::getId, Comparator.reverseOrder());
좋은 의견 감사합니다! 케이님 코멘트대로 쿼리 단에서 정렬하니 코드가 깔끔해지네요 👍
limit 조건에 대해서는 성능 체크 해봤는데 지금처럼 서비스에서 하는 게 더 좋다고 생각해서 그대로 두겠습니다

2023-06-10 05:14 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        List<CafeImageResponse> slicedCafeImages = sortedCafeImages.subList(startIndex, endIndex);
일단 수정된 코드로 index 테스트 해보니 에러가 뜨지는 않습니다. 다시 한 번 인덱스 에러가 나는지 확인해주시면 감사합니다!

2023-06-10 05:20 UTC, kth990303 commented on src/main/java/mocacong/server/repository/CafeImageRepository.java
> +    Slice<CafeImage> findAllByCafeIdAndIsUsedOrderByCafeImageIdDesc(Long cafeId, Pageable pageable);
`@Query` 어노테이션을 짰으니 RepositoryTest 작성하면 좋을듯하네요.

RepositoryTest 가 필요한 이유
- Service Test 에서 동작 확인이 됐다고 하자.
- 타, 서비스에서 해당 쿼리를 이용했을 때 의도대로 동작이 안된다면?
- 쿼리를 잘못짠건지, 비즈니스 로직을 잘못짠건지 확인해봐야된다. 해당 메서드 상황에서만 우연히 쿼리가 의도대로 동작한 것일 수 있기 때문

2023-06-10 05:20 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        List<CafeImageResponse> slicedCafeImages = sortedCafeImages.subList(startIndex, endIndex);
수정된 코드는 에러가 나지 않을 거예요.
페이지네이션 직접 짠 코드에서는 index가 범위초과가 나서 에러가 뜨게 되는 거였습니다. 직접 페이지네이션을 짤 경우 고려할 게 좀 많을 거예요

2023-06-10 05:21 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +                .thenComparing(CafeImageResponse::getId, Comparator.reverseOrder());
성능 체크 진행방법이랑 결과가 궁금합니다. 기록해주시면 좋을거같아요~

2023-06-10 05:37 UTC, kth990303 requested changes
Slice 를 도입하니 코드가 한결 나아졌네요.
`isMe`가 정렬조건 최우선이지 않아서 RC로 남겼어요

2023-06-10 05:37 UTC, kth990303 commented on src/main/java/mocacong/server/repository/CafeImageRepository.java
> +    Slice<CafeImage> findAllByCafeIdAndIsUsedOrderByCafeImageIdDesc(Long cafeId, Pageable pageable);
최신순이 최우선이 아닌, `isMe`가 true인 것이 최우선으로 order by가 돼야 합니다.

### 결과
<img width="755" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/addd0d00-aa70-4f52-a784-32c9241ba5a1">

### 프론트 요구사항
<img width="379" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/d0f1de14-3ecc-4f1b-921e-94ae70a49d4d">

2023-06-10 05:37 UTC, kth990303 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +    void findCafeImagesReturnOrderedImages() throws IOException {
타인이 등록한 이미지는 이후에 보여지는 테스트도 있으면 좋을거 같아요

2023-06-10 06:36 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +                .thenComparing(CafeImageResponse::getId, Comparator.reverseOrder());
![image](https://github.com/mocacong/Mocacong-Backend/assets/69844138/507c3702-c8a0-43d6-be66-6aeaca569301)
![image](https://github.com/mocacong/Mocacong-Backend/assets/69844138/b88a9807-79b7-4fa1-aadc-95affd690764)

datagrip으로 레포지토리 단에서 작성한 쿼리문 가지고 체크했습니다. 다시 확인해보니 limit를 건 게 실행속도가 더 빨라서 `List<CafeImage> findAllByCafeIdAndIsUsedOrderByCafeImageIdDesc` 는 limit를 추가하는 게 좋을 거 같네요.

2023-06-10 14:11 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        List<CafeImageResponse> slicedCafeImages = sortedCafeImages.subList(startIndex, endIndex);
아하 웬만하면 `Pageable` 이용해서 해야겠네요 🫠

2023-06-10 14:12 UTC, Ji-soo708 commented on src/main/java/mocacong/server/repository/CafeImageRepository.java
> +    Slice<CafeImage> findAllByCafeIdAndIsUsedOrderByCafeImageIdDesc(Long cafeId, Pageable pageable);
지적 감사합니다. 바로 추가하겠습니다~

2023-06-10 14:12 UTC, Ji-soo708 commented on src/main/java/mocacong/server/repository/CafeImageRepository.java
> +    Slice<CafeImage> findAllByCafeIdAndIsUsedOrderByCafeImageIdDesc(Long cafeId, Pageable pageable);
저 부분 처리를 깜빡했네요. 수정해서 다시 올리겠습니다~

2023-06-10 14:20 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        Pageable pageable = PageRequest.of(0, 5);
`.limit` 대신 페이지네이션을 통해 5개까지만 조회하도록 했습니다.

2023-06-10 14:20 UTC, Ji-soo708 commented on src/main/java/mocacong/server/repository/CafeImageRepository.java
> +    @Query("SELECT ci FROM CafeImage ci WHERE ci.cafe.id = :cafeId AND ci.isUsed = true " +
현재 서비스 코드 로직에서는 이미지들을 먼저 정렬하고 이후에 `isMe` boolean 값을 정합니다. 그렇기에 `@Query` 에서는 CASE문을 통해 자신의 이미지부터 먼저 조회하도록 작성했습니다.

2023-06-11 02:15 UTC, kth990303 approved these changes
좋습니다 approve 할게요~
코멘트 확인 후 적절한 시점에 머지하시면 될듯합니다

2023-06-11 02:15 UTC, kth990303 commented on src/main/java/mocacong/server/repository/CafeImageRepository.java
> +    @Query("SELECT ci FROM CafeImage ci WHERE ci.cafe.id = :cafeId AND ci.isUsed = true " +
쿼리 잘짜주셨네요. `isMe`가 쿼리단에서 결정되니까 아예 여기서 isMe까지 반환하도록 해도 괜찮을 거 같아요. 이후에 DTO projection으로 감싸줘도 괜찮을 거 같습니다.

2023-06-11 02:15 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        return cafeImageResponses;
취향차이겠지만 cafeImageResponses를 인라인 변수로 안받고 바로 return 해도 괜찮아보이네요

```java
Slice<CafeImage> cafeImages = cafeImageRepository.
        findAllByCafeIdAndIsUsedOrderByCafeImageIdDesc(cafe.getId(), member.getId(), PageRequest.of(0, 5));

return cafeImages
        .getContent()
        .stream()
        .map(cafeImage -> {
            Boolean isMe = cafeImage.isOwned(member);
            return new CafeImageResponse(cafeImage.getId(), cafeImage.getImgUrl(), isMe);
        })
        .collect(Collectors.toList());
```

2023-06-11 02:15 UTC, kth990303 commented on src/main/java/mocacong/server/repository/CafeImageRepository.java
> +    @Query("SELECT ci FROM CafeImage ci WHERE ci.cafe.id = :cafeId AND ci.isUsed = true " +
### 인덱스 관련 코멘트
`cafe_id`, `is_used`을 where절로 필터링한 후, `member_id`, `cafe_image_id`로  order by 정렬을 해서 `extra`에 `Using filesort`가 들어가네요. 

아래 옵션대로 인덱스를 추가할까 고민중이긴 해요.
```sql
CREATE INDEX cafe_image_filter_index ON cafe_image (cafe_id, is_used, member_id, cafe_image_id);
```
(필터링 조건 + 정렬 조건) 으로 인덱스 설정.
하지만 생각보다 성능차가 크게 나지 않아서 일단 보류할게요.
7~8월 달에 성능 개선하실 때 해당 코멘트 인지 후 설정 여부 최종결정하시면 될거같아요

### 인덱스 추가 전
`Using where; Using filesort`
<img width="989" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/a6ec3c3f-f561-49ff-acbd-3298420faa39">

### 인덱스 추가 후
`Using filesort`
<img width="985" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/826c3469-4626-4a02-9657-aba815b92007">

2023-06-11 16:30 UTC, Ji-soo708 commented on src/main/java/mocacong/server/repository/CafeImageRepository.java
> +    @Query("SELECT ci FROM CafeImage ci WHERE ci.cafe.id = :cafeId AND ci.isUsed = true " +
음 생각보다 차이가 근소하네요. 나중에 다른 쪽에서 인덱스 적용 전후 차이 좀 있는 경우가 있다면 그때 같이 인덱스 적용하면 좋을 거 같아요. 👍

2023-06-11 16:31 UTC, merged