feat: README 파일 작성
mocacong/Mocacong-Backend pull request #112
Opened 2023-06-25 12:26 UTC by kth990303

## 개요
- 리드미 파일이 존재하지 않아, 해당 레포지토리에서 어떤 작업을 하고 무슨 애플리케이션을 만드는지 알기가 어렵습니다.

## 작업사항
- github README 파일을 작성했습니다.
[작업 결과 확인](https://github.com/mocacong/Mocacong-Backend/tree/MOCACONG-354-%EB%B0%B1-Github-README)

## 주의사항
- 디자인 수정할 점이 있으면 **수정사항과 함께** 남겨주세요. 마크다운으로 예쁘게 작성하는 법을 모르겠어요
- 추가됐으면 좋겠다고 생각되는 내용이 있으면 리뷰해주세요
- 틀린 내용이 있는지 확인해주세요

2023-06-25 14:45 UTC, Ji-soo708 requested changes
글자 크기 관련이랑 erd 내용도 추가하는 거 어떨지 싶어서 코멘트 남겼습니다! 정말 수고하셨어요~ 👏

2023-06-25 14:45 UTC, Ji-soo708 commented on README.md
> +# 모각코하기 좋은 카페 지도 애플리케이션, 모카콩(MOCACONG)
`##` 으로 글자 크기 줄이는 거 어떠신가요? 제목이 길어서인지 글자가 유독 커보여요!

2023-06-25 14:45 UTC, Ji-soo708 commented on README.md
> +# 모각코하기 좋은 카페 지도 애플리케이션, 모카콩(MOCACONG)
아래 `#` 들이 붙은 제목들 다 한단계씩 글자 크기 줄이면 좋을 거 같아요~

2023-06-25 14:45 UTC, Ji-soo708 commented on README.md
> +
이 사이에 저희 최종 보고서 작성할 때 만든 ERD 사진 추가하는 거 어떨까요?

2023-06-26 00:36 UTC, kth990303 commented on README.md
> +
좋아요 ERD 추가했습니다

2023-06-26 00:36 UTC, kth990303 commented on README.md
> +# 모각코하기 좋은 카페 지도 애플리케이션, 모카콩(MOCACONG)
제목은 h2, 소제목은 h3로 변경했습니다

2023-06-26 01:10 UTC, Ji-soo708 approved these changes

2023-06-28 08:56 UTC, Ji-soo708 requested changes

2023-06-28 08:56 UTC, Ji-soo708 commented on README.md
> +<p align="center">
사진 일렬로 4개 줄 세우는 건 별로일까요? 사진이 4개라 사진 크기 줄이고 한 줄에 다 넣으면 더 깔끔할 거 같아서요!

2023-06-28 09:24 UTC, kth990303 commented on README.md
> +<p align="center">
```markdown
<p align="center">
  <img width="23%" height="400" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/b8510091-a49a-439d-b067-eb92afe282ab">
  <img width="23%" height="400" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/ed9d723f-8161-4de4-9dae-3cfc2eea43b1">
  <img width="23%" height="400" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/614c6e44-9199-4042-9f29-b90f659dc613"> 
  <img width="23%" height="400" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/a81d4fbd-a4a4-4ebb-bc63-c8e0e815e2cb">
</p>
```

위 코드로 바꿔볼까요?

<img width="1494" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/b3d84719-946f-480d-81c8-06d84d0e10e2">

사진 사이즈 괜찮은지 확인해주시고 괜찮으면 수정할게요

2023-06-28 11:12 UTC, kth990303 commented on README.md
> +<p align="center">
위 코드에서 추가로 20%로 줄여서 커밋했습니다~

2023-06-28 11:18 UTC, jung-woo-kim requested changes
리드미 확인했습니다! 다 깔끔하고, 기술 스택 추가하면 좋을 것 같아서 그것만 리뷰 남겼습니다.
고생하셨어요! 👍👍

2023-06-28 11:18 UTC, jung-woo-kim commented on README.md
> +- `Performance Test`: nGrinder
사용 기술 스택에 redis 추가하면 좋을 것 같아요!

2023-06-29 00:33 UTC, jung-woo-kim approved these changes
변경내용 확인했습니다! 고생하셨어요~

2023-06-29 00:34 UTC, Ji-soo708 approved these changes

2023-06-29 01:35 UTC, merged

2023-06-29 09:00 UTC, roseroirequin reviewed
고생하셨습니다!

2023-06-29 09:00 UTC, roseroirequin commented on README.md
> +</p>
고생하셨습니다!