feat: 공백 값에 대한 토큰 공백 커스텀 예외 처리 추가
mocacong/Mocacong-Backend pull request #118
Opened 2023-07-05 08:29 UTC by Ji-soo708

## 개요
- 기존 `extractAccessToken` 는 `request` 로 들어온 토큰 값이 공백이 아닌지에 대한 검증 로직을 포함하지 않았습니다. `extractAccessToken` 로직에서 분할된 헤더 값이 두 개 이상(인증 유형 + 토큰)인지 확인하여 헤더 값이 하나인 경우(공백 토큰) `BlankTokenException` 예외를 반환하도록 했습니다.

## 작업사항
- `BlankTokenException` 커스텀 예외 추가
- `extractAccessToken` 로직에서 공백 값에 대한 토큰 공백 커스텀 예외 처리 추가
- `BlankTokenException` 예외 반환 테스트 코드 추가

## 주의사항
- 포스트맨으로 해당 예외가 잘 반환되는지 확인해주세요
- 더 좋은 로직이 있다면 추천해주세요

2023-07-05 08:32 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +                if (parts.length > 1) {
"인증 유형 + 토큰"의 형식인 경우에 토큰이 제대로 들어온 것이므로 parts의 길이가 2 이상인지 체크하여 공백 토큰이 아닌지를 검증합니다.

2023-07-05 08:32 UTC, Ji-soo708 commented on src/test/java/mocacong/server/security/auth/AuthorizationExtractorTest.java
> +        MockHttpServletRequest request = new MockHttpServletRequest();
`MockHttpServletRequest` 를 사용하여 가짜로 요청 객체를 생성하고 필요한 헤더 값을 설정하여 테스트했습니다. 더 좋은 테스트 로직이 있다면 코멘트 남겨주세요.

2023-07-05 08:50 UTC, Ji-soo708 commented on src/test/java/mocacong/server/security/auth/AuthorizationExtractorTest.java
> +}
crlf 문제인 거 같은데 해결하고 다시 커밋하겠습니다.

2023-07-05 09:04 UTC, jung-woo-kim approved these changes
pr 확인했습니다!
로직 잘 짜주셨네요 👍 
메서드 depth와 if-else 분기에 대해서 리뷰 남겼으니 확인 부탁드려요~

2023-07-05 09:04 UTC, jung-woo-kim commented on src/test/java/mocacong/server/security/auth/AuthorizationExtractorTest.java
> +        MockHttpServletRequest request = new MockHttpServletRequest();
`MockHttpServletRequest` 사용한 부분 좋은 것 같아요. 👍

2023-07-05 09:25 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +                }
일부러 else 로 뺀 이유가 공백 예외인지 자세히 알려주기 위해서 였는데 depth를 고려해서 공백인 경우에도 `InvalidBearerException`을 던져도 좋을 거 같네요. 👍
그런데 validateToken 메서드를 추출하면 좋다는게 getPayload 메서드랑 겹치는 로직을 따로 메서드로 추출해서 호출하면 좋다는 말씀이신가요??

2023-07-05 09:32 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +                }
아 그런데 이렇게 하면 `로그인이 필요한 서비스입니다.`라고 반환되는데 이렇게 넘겨도 프론트측에서 괜찮을 지 고민이네요..

2023-07-05 09:33 UTC, jung-woo-kim commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +                }
아뇨! `BlankTokenException()` 와 같이 자세한 예외를 그대로 이용하게 된다면 
가령 위 로직을
```
private void validateParts(String[] parts) {
        if (parts.length <= 1) {
            throw new BlankTokenException();
        }
    }
```
와 같이 메서드 추출하면 조금 가벼워질 것 같아서 말씀 드렸어요!
너무 모호하게 말씀드렸네요 😥

2023-07-05 09:37 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +                }
아하 이해됐습니다. 이 방법이 가독성도 더 좋은 거 같네요 ㅎㅎ 지적 감사합니다~

2023-07-06 00:49 UTC, kth990303 approved these changes
되게 잘 수정해주셨습니다 ㅎㅎ
다만 토큰값에 공백이 들어갈 수 없는 점을 고려하면, 아예 공백을 제거시키는건 어떨까? 하는 마음이 들었어요. 

이왕 `AuthroizationExtractor` 건드리는 김에, 검증 빡세게 체크하면 좋을 거 같다는 생각에 추가 코멘트를 남겨봤습니다. RC와 approve 중에서 고민 매우 하다가... 일단 공백 자체는 막으므로 approve로 할까? 하다가 잘못된 요청에 대해 500번대 에러 반환하므로 조금 더 살펴봐주시면 좋을듯해서 RC로 바꿨어요

2023-07-06 00:49 UTC, kth990303 commented on src/main/java/mocacong/server/exception/badrequest/BlankTokenException.java
> +    }
컨플루언스 에러 커스텀 명세에도 기입 부탁드립니다

2023-07-06 00:49 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +    }
토큰 값이 `  2  ` (공백 여러개 + 문자) 와 같은 케이스를 막을 수 없어보여요.

<img width="966" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/8079e92b-076b-4903-b35b-2ccf461bc9fb">

<img width="642" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/15f8b2b1-90af-4150-9806-18f8ddea46fd">

2023-07-06 00:49 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +                return parts[TOKEN_INDEX];
만약 조금 더 빡세게 검증을 원한다면 아래 로직도 괜찮아보여요

```java
package mocacong.server.security.auth;

import lombok.NoArgsConstructor;
import mocacong.server.exception.badrequest.BlankTokenException;
import mocacong.server.exception.unauthorized.InvalidBearerException;

import javax.servlet.http.HttpServletRequest;
import java.util.Enumeration;

@NoArgsConstructor
public class AuthorizationExtractor {

    private static final String AUTHENTICATION_TYPE = "Bearer";
    private static final String AUTHORIZATION_HEADER_KEY = "Authorization";
    private static final int START_TOKEN_INDEX = 6;

    public static String extractAccessToken(HttpServletRequest request) {
        Enumeration<String> headers = request.getHeaders(AUTHORIZATION_HEADER_KEY);
        while (headers.hasMoreElements()) {
            String value = headers.nextElement();
            // Bearer 문자열이 포함됐을 경우
            if (value.toLowerCase().startsWith(AUTHENTICATION_TYPE.toLowerCase())) {
                // 문자열에서 공백 제거, Bearer 이후 문자열만 체크
                String extractToken = value.trim().substring(START_TOKEN_INDEX);
                validateExtractToken(extractToken);
                return extractToken;
            }
        }
        throw new InvalidBearerException();
    }

    private static void validateExtractToken(String extractToken) {
        // 공백이면 예외 반환
        if (extractToken.isBlank()) {
            throw new BlankTokenException();
        }
    }
}

```

2023-07-06 00:52 UTC, kth990303 requested changes
원래 approve 였는데, 생각해보니 잘못된 요청에 대해 500번대를 반환하긴 하므로 RC로 바꿀게요 😂

2023-07-06 02:33 UTC, Ji-soo708 commented on src/main/java/mocacong/server/exception/badrequest/BlankTokenException.java
> +    }
넵 기입해있습니다!

2023-07-06 02:36 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +                return parts[TOKEN_INDEX];
사실 토큰을 보낼 때 문자열에 공백이 포함되어 있는 채로 안보내겠지 싶어서 공백만 들어오는 경우만 고려했는데 케이님 코멘트처럼 저렇게 검증을 빡세게 해도 좋다고 생각합니다. 👍

2023-07-06 03:11 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
> +                String extractToken = value.trim().substring(START_TOKEN_INDEX);
`trim()` 을 통해 해당 문자열이 공백인지 체크했습니다.

2023-07-06 03:19 UTC, kth990303 approved these changes
확인했어요~ 수고했습니다

2023-07-06 04:49 UTC, jung-woo-kim approved these changes
변경 확인했습니다! trim() 사용 좋네요 👍

2023-07-06 04:50 UTC, merged