feat: 댓글 좋아요 등록 기능 구현
mocacong/Mocacong-Backend pull request #122
Opened 2023-07-11 09:34 UTC by jung-woo-kim

## 개요
- 댓글 좋아요 등록 기능이 추가되었습니다.

## 작업사항
- 댓글에 좋아요한 유저의 정보를 담기위한 CommentLike 테이블을 새롭게 생성하였습니다.
- 한 유저가 한 댓글에 여러번 좋아요할 수 없도록 데이터베이스 unique 무결성 제약을 걸어 동시성을 고려하였습니다.
- 추가로 동시성 테스트도 구현하였습니다.
- 스웨거로 정상 동작하는지 확인하였습니다.

## 주의사항
- 댓글 좋아요에 cafes의 mapId가 필요없어 path가 바뀌게 되었는데, 혹시 더 좋은 방법이 있다면 말씀해주세요.
- 동시성 테스트에 더 좋은 방법이 있다면 추천해주세요.

2023-07-12 14:22 UTC, kth990303 requested changes
지나가다가 들렀습니다 ㅋㅋ
댓글에 좋아요 기능이 생기는군요. 아직 조회는 없나보네요 ㅎㅎ
500번대 예외 터질만한 크리티컬한 상황이 보여서 RC 남겼습니다

2023-07-12 14:22 UTC, kth990303 commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +        commentLikeRepository.deleteById(commentLikeId);
만약 좋아요가 달린 댓글이 삭제된다면 어떻게 될까요?
댓글이 삭제되는 경우에도 이벤트를 전파해주는 게 좋아보이네요

<img width="594" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/32df5d83-0202-40d5-84d0-224f1c467859">

2023-07-12 14:22 UTC, kth990303 commented on src/main/java/mocacong/server/domain/CommentLike.java
> +public class CommentLike {
새로운 테이블 생성됐으니 머지되면 개발DB에 create 부탁드립니다!
(만약 이 작업이 귀찮다면? DB 형상관리 툴 Flyway나 Liquibase를 사용해보는 건 어떨까요?)

2023-07-12 18:37 UTC, Ji-soo708 requested changes
동시성 관련이랑 테스트 코드 관련해서 코멘트 달았습니다. 기능 구현하시느라 수고하셨어요~

2023-07-12 18:37 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +            return new CommentLikeSaveResponse(commentLikeRepository.save(commentLike).getId());
본인이 작성한 댓글에 대해 좋아요를 남길 수 없도록 막지는 않으셨는데 이 부분은 프론트와 아직 얘기 안 나눴던 거 같네요.
에브리타임같은 앱에서도 본인이 남긴 댓에는 좋아요를 못누르도록 막기때문에 저희 서비스에서도 해당 경우에 대해 좋아요 등록을 막는 게 좋을 거 같은데 어떻게 생각하시나요

2023-07-12 18:37 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +    public CommentLikeSaveResponse save(Long memberId, Long commentId) {
<img width="985" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/69844138/7a2be513-6fad-4368-a63c-4f28e2477a2a">
스웨거에서 한 댓글에 대해 좋아요 기능을 빠르게 여러번 호출하니까 `unique constraint`가 걸려있는데도 좋아요 id가 3~5개씩 생기네요.(사진은 여러번 테스트한 결과입니다)  
`unique constraint`가 이 부분까지 막긴 힘든걸까요. 🤔

2023-07-12 18:37 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CommentLikeServiceTest.java
> +class CommentLikeServiceTest {
케이님이 남겨주신 '좋아요가 달린 댓글을 삭제하는 경우'에 생기는 문제를 해결하시고 이 경우에 대한 테스트코드 추가로 작성하시면 좋을 거 같아요 👍

2023-07-13 09:52 UTC, jung-woo-kim commented on src/test/java/mocacong/server/service/CommentLikeServiceTest.java
> +class CommentLikeServiceTest {
테스트 케이스는 CommentServiceTest에 있는 것이 적절한 것 같아 CommentServiceTest에 남겨두었습니다!

2023-07-13 09:52 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +            return new CommentLikeSaveResponse(commentLikeRepository.save(commentLike).getId());
이 부분 적용해서 푸쉬해놨습니다! 확인 감사해요 🙂

2023-07-13 09:52 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +        commentLikeRepository.deleteById(commentLikeId);
해결해서 푸쉬해놨습니다! 확인 감사해요 🙂

2023-07-13 14:46 UTC, kth990303 commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +    public CommentLikeSaveResponse save(Long memberId, Long commentId) {
> id 값이 유니크 제약을 걸린 만큼 증가하는 것은 바람직하지 않은 것 같아 아래 무결성 제약 앞단에 중복을 한번 더 확인하는 로직 추가해놨습니다!

의미가 있을진 사실상 미지수이긴 한게, 동시성을 뚫을 정도로 빠른 호출이면 애플리케이션 코드 단에서의 체크로직은 뚫립니다.
그래도 나쁘지 않은 시도일 듯 하네요

2023-07-13 15:09 UTC, kth990303 approved these changes
코드리뷰 반영 확인했습니다.
궁금한 점 남겨봤는데 댓글 부탁드려요~
approve 하겠습니다

2023-07-13 16:01 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +    }
- 우선 현재도 댓글삭제가 진행된 후에 댓글 좋아요가 삭제된다고 봤습니다! @TransactionalEventLister의 TransactionPhase 기본 값이 After Commit이기 때문에 그렇게 생각했어요! 

- @TransactionalEventLister 사용 시 하나의 싱글 스레드 내에서 두개의 물리 트랜잭션이 두번 commit 됩니다. 즉, 댓글 삭제와 상관 없는 트랜잭션으로 인하여 사용자에게 응답이 늦게 갈 수 있습니다. 새로운 스레드를 생성하여 비동기로 실행하여 댓글 좋아요에 대한 응답은 사용자에게 빠르게 가게 하기 위해 성능 상의 이점을 챙기려했어요.

- @EventLister 사용 시 트랜잭션이 분리가 되지 않습니다. 따라서 한 트랜잭션 내에서 댓글 좋아요의 삭제와 댓글의 삭제가 함께 되게 되는데요. 만약에 둘다 `TransactionalEventListener` 안에 있다고 가정해보겠습니다. **댓글 삭제는 정상적으로 수행되는데,  `deleteFavoritesWhenMemberDeleted`의 기능에 모종의 문제가 생겨 rollback되게 된다면 댓글 삭제 정보 자체가 rollback되어 댓글 삭제 기능 자체가 동작하지 않게 됩니다.**  `deleteFavoritesWhenMemberDeleted`의 기능은 비즈니스 로직과는 크게 영향이 없는 그저 db에서 null인 것들을 삭제하는 것인데, `deleteFavoritesWhenMemberDeleted`에 의해서 비즈니스 로직인 댓글 좋아요 취소가 망가지게 됩니다. 즉, 비즈니스 로직과는 크게 관련 없는 `deleteFavoritesWhenMemberDeleted`를 트랜잭션 분리하여 수행하여 위 문제를 해결했습니다. (당연히 `deleteAllWhenCommentDelete`가 롤백된다면 댓글 좋아요 삭제가 실패한 것이므로 트랜잭션을 롤백하는게 옳다고 생각했습니다.)

음.. 너무 어렵게 설명한 것 같은데 간단히 말씀드리면 `deleteFavoritesWhenMemberDeleted` (댓글 좋아요 기능과 크게 관련이 없는 작업 )를 트랜잭션에서 분리함으로써 실패해도 댓글 좋아요 기능이 정상적으로 돌아가게 하기 위함입니다!

2023-07-13 16:01 UTC, jung-woo-kim commented on src/main/java/mocacong/server/exception/badrequest/InvalidCommentLikeException.java
> +        super("자신의 댓글에 좋아요할 수 없습니다.", 6002);;
빠르게 고치겠습니다,, 장염 이슈로 집중력이 현저히 낮네요 🥲🥲

2023-07-14 11:01 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +    public CommentLikeSaveResponse save(Long memberId, Long commentId) {
> 관련해서 [Mysql 공식 문서](https://dev.mysql.com/doc/refman/8.0/en/innodb-auto-increment-handling.html)를 뒤져본 결과, 유니크 제약이 걸려도 일단은 id 값을 증가 시킨다고 합니다! 즉, 동시성은 지켜지는데 id 값은 증가합니다.
> 
> id 값이 유니크 제약을 걸린 만큼 증가하는 것은 바람직하지 않은 것 같아 아래 무결성 제약 앞단에 중복을 한번 더 확인하는 로직 추가해놨습니다!

오 이건 처음 아는 사실이네요! ㅎㅎ 케이님 코멘트보니까 완전히 막는 건 불가능하니까 어쩔 수 없네요 🥲

2023-07-14 11:06 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +    }
오.. 코드 보면서 저렇게까지 생각은 안했는데 케이님이랑 베어님 코멘트 보면서 많이 공부해갑니다...

2023-07-14 11:21 UTC, Ji-soo708 approved these changes
수정사항 확인해서 approve합니다~ 저도 스프링 열공해서 코드리뷰로 얘기 나누고 싶네요 🙃🙃 수고하셨습니다!

2023-07-14 13:07 UTC, kth990303 commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +    }
롤백이 되더라도 null 처리는 유지시키려는 거였군요 확인했습니다. rollback이 만약 발생한다면 retry 처리도 혹시 계획중이실까요?

2023-07-14 13:08 UTC, kth990303 commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +    }
그리고 approve 상태이기 때문에 머지하시고 코멘트 남기셔도 상관없습니다~~

2023-07-14 14:34 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentLikeService.java
> +    }
롤백이 됐을 때 Async로 다른 스레드에서 동작되기 때문에 ControllerAdvice에서 잡지 못할 것 같은데 retry 처리 생각은 못했네요,, 

AsyncConfig에 getAsyncUncaughtExceptionHandler() 등의 처리로 해당 코드의 오류는 슬랙에 심각한 오류 알람을 준다거나 해야하는 필요성이 느껴지네요. 😦

2023-07-14 14:35 UTC, merged