feat: 코멘트 신고 기능 POST API 구현
mocacong/Mocacong-Backend pull request #123
Opened 2023-07-11 20:38 UTC by Ji-soo708

## 개요
- 댓글을 신고할 수 있는 코멘트 신고 기능을 추가했습니다. 그에 따라 자체 로그인/OAuth 로그인 시에 반환하는 response에 필드를 추가했습니다.

## 작업사항
- 댓글 신고에 대한 정보를 저장하는 CommentReport 엔티티 추가
  - 해당 엔티티를 통해 동일한 댓글에 대해 동일한 회원이 중복 신고가 불가능하도록 처리
- 회원 상태를 나타내는 Status Enum 추가
- Comment 엔티티에 CommentReport의 List를 나타내는 `reports` 컬럼 추가
- Member 엔티티에 유저 신고 횟수를 나타내는 `reportCount` 컬럼 추가
- Member 엔티티에 회원 상태를 나타내는 `status` 컬럼 추가
- 코멘트에 신고 10회가 들어온 경우에 대해 처리 로직 추가
  - 해당 코멘트 삭제 처리 로직 추가
  - 해당 코멘트를 작성한 회원에게 경고 처리 추가
- 사용자 경고가 11개 이상 누적된 경우 60일간 기간 정지하는 로직 추가
  - 60일간의 기간동안 해당 회원의 `status` 를 `INACTIVE` 로 변경
  - `INACTIVE`인 기간 동안 모카콩 서비스에 로그인 불가
- 스케줄링을 통한 회원 상태 관리 로직 추가
  - 60일간의 기간동안 `INACTIVE`였던 회원의 `status` 를 `ACTIVE` 로 변경 
  - `status` 가 `ACTIVE` 로 변경된 회원의 `reportCount` 값을 0으로 초기화
 - 위의 변경사항에 따른 `TokenResponse`, `OAuthTokenResponse`에 `status`, `userReportCount` 필드 추가
 - `Status` 도입으로 인한 로그인 관련 서비스 코드 변경
 - 코멘트 신고 기능 관련 단위 테스트 및 인수 테스트 코드 작성
 - `Status` 도입으로 인한 로그인 관련 단위 테스트 코드 추가

## 주의사항
- 해당 PR은 프론트의 요청에 따라 Response 필드가 바뀔 수 있습니다. Review Request를 날린 후에 코드리뷰를 남겨주세요
- 기본적으로 아래의 기능들에 대해 스웨거를 통해 테스트를 했으나 중요한 기능들은 한번 더 로컬에서 테스트해주세요.
  - 한 코멘트에 대해 한 사람당 한 번만 신고가 가능한지
  - 자신의 코멘트에 신고를 시도하면 예외가 반환되는지
  - 코멘트 누적 신고 횟수가 10회이면 삭제 처리가 되는지
  - 코멘트 누적 신고 횟수가 10회이면 해당 코멘트를 작성한 `reportCount`가 하나씩 증가하는지
  - 11개 이상의 사용자 경고가 들어오면 해당 회원은 해당 기간동안 모카콩 서비스에 로그인을 못하는지
  - 스케줄링 작업을 통해 해당 기간이 지난 `INACTIVE` 회원에 한해 `ACTIVE` 로 `status`가 변경되는지 
  - 해당 기간을 지나 `ACTIVE` 로 변경된 회원의 `reportCount`가 0으로 초기화 되는지
- 깃허브에 올라온 스케줄링 작업 코드는 자정마다 `modifiedTime` 기준으로 60일이 지난 `INACTIVE` 회원에 한해 배치 작업을 수행하고 있습니다. 로컬에서 스케줄링 관련 기능을 테스트한다면 `BatchConfig` 코드를 수정해서 테스트하셔야 합니다.
- OAuth 로그인 관련 로직이 제대로 수정되었는지 확인해주세요
- 누락된 테스트가 있는지 확인해주세요
- 더 나은 로직이 있다면 알려주세요

2023-07-11 20:53 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/BatchConfig.java
> +    @Scheduled(cron = "0 0 0 * * *", zone = "Asia/Seoul") // 매일 자정에 실행
해당 메서드에서 매일 자정마다 60일 간 `INACTIVE`였던 회원들에 한 해 다시 상태를 활성화 시킵니다.

2023-07-11 20:53 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/CommentReport.java
> +public class CommentReport {
한 코멘트에 대해 한 유저가 여러 번의 신고하는 것을 막기 위해 Comment와 신고한 유저 reporter의 관계를 나타내는 `CommentReport` 엔티티를 생성했습니다

2023-07-11 20:53 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Member.java
> +    private Status status;
해당 `status`를 통해 현재 활동중인 회원과 기간 정지 당한 회원을 구분짓습니다.

2023-07-11 20:53 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Member.java
> +    private int reportCount;
회원이 경고 받은 횟수

2023-07-11 20:53 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Member.java
> +        if (status == Status.ACTIVE) { // 정지를 푸는 경우
스케줄링을 통해 기간 정지가 풀린 회원은 `MemberReportCount`가 초기화됩니다.

2023-07-11 20:53 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/AuthService.java
> +    private void validateStatus(final Member findMember) {
해당 메서드를 통해 `ACTIVE` 상태인 회원만 로그인이 가능하도록 처리합니다.

2023-07-11 20:53 UTC, Ji-soo708 commented on src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
> +    @DisplayName("타인이 작성한 코멘트를 신고한다")
코멘트 신고에 대한 자세한 테스트들은 단위 테스트에서 진행하고 인수 테스트에서는 1개만 추가했습니다.

2023-07-11 20:53 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CommentServiceTest.java
> +        for (int i = 1; i <= 11; i++) {
일일이 10번이상 코드를 복붙하는 건 안예뻐서 for문 돌렸는데 더 좋은 방법이 있다면 알려주세요..

2023-07-13 17:19 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/CommentReport.java
> +    private ReportReason reportReason;
신고사유 컬럼을 추가했습니다.

2023-07-14 15:44 UTC, jung-woo-kim requested changes
엄청나게 할 일이 많으셨을 것 같은데, 고생하셨네요 😰
우선 크게 report 관련 컨트롤러와 Service를 분리하면 좋을 것 같다는 생각이 드네요.
또, 동시성 이슈가 날 상황도 있고 무결성 제약 조건 관련 오류를 발생할 상황이 보여 우선 RC 날립니다!

테스트 등의 수행은 다음 review request 주시면 확인해볼게요!

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/domain/Comment.java
> +
Comment에서 getReports메서드가 불리는 부분은 없어보이네요. 우선은 양방향 연관관계는 없애도 될 것 같아요.

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/controller/CommentController.java
> +    }
코멘트 신고에 cafe map Id가 필요하지 않은 것 같아요.
commentId만 있어도 CommentRepository에서 findById로 원하는 Comment를 찾을 수 있을 것 같아요.

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/config/BatchConfig.java
> +    }
자정에 이용하는 사람이 많이 없어 critical 하진 않을 것 같은데 update를 여러사람마다 하기보다 벌크 연산을 통해 한번에 update해보는 것은 어떤가요? 신고 당하는 회원이 많지 않을 것이라 예상되어 괜찮을 것 같긴 합니다 🤔

추가로 service 로직으로 빼서 처리하면 더 좋을 것 같아요!

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/domain/Comment.java
> +    }
else문은 제거 가능할 것 같아요.
```suggestion
    public void incrementCommentReport(Member reporter, String reportReason) {
        if (!hasAlreadyReported(reporter)) {
            ReportReason reason = ReportReason.from(reportReason);
            this.reports.add(new CommentReport(this, reporter, reason));
        }
        throw new DuplicateReportCommentException();
    }
```

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/dto/response/CafeImageSaveResponse.java
그때는 생각 못했긴 했는데, 응답에 user의 신고횟수를 담아서 해결하는 부분이 조금 이상해 보이긴 하네요 🤔
일단 이 부분 보류해두고 refreshToken 사용 시 멤버의 상태를 함께 보내 프론트 단에서 로그아웃 시키고 로그인 시에 Member의 상태를 확인해서 login을 서버 측에서 막는 것이 좋아보이네요. refreshToken이 도입되기 전까진 보류해야할 것 같긴 합니다.

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/exception/badrequest/InvalidReportReasonException.java
> +        super("신고 사유 정보가 올바르지 않습니다.", 6000);
6000번대 에러 댓글 좋아요일거에요. 동시 작업이라 겹쳤나보네요 😰

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/security/auth/apple/AppleOAuthUserProvider.java
> +
미사용 변수 같아요!

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
> +
미사용 변수 같아요!

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentService.java
> +                .orElseThrow(NotFoundCommentException::new);
Controller에 리뷰 남긴대로 굳이 카페 신고에 mapId가 필요할 것 같진 않아요! findById를 활용해 leftOuterjoin, cafe 조회 등 쿼리 성능을 개선할 수 있어보여요

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentService.java
> +            }
여기 코드 한번에 이해하기에 어려운 것 같아요.
우선, `commenter.incrementMemberReportCount();`를 이렇게 관리할 필요가 있을까요?? 
Comment에 memberId fk로 있기 때문에 멤버의 reportedCount는 언제든 구할 수 있을 것 같아요.

또, `commenter.incrementMemberReportCount();` 부분 동시성 이슈가 터질 확률이 있어보이네요.
동시에 두 사람이 신고한다고 했을 때 reportCount+=1이 동시에 수행되면 1만 증가된 값이 들어올 수 있어보이네요.
reportCount 컬럼 삭제하고 쿼리로 유저가 신고 당한 횟수 세는게 좋아보여요.

이렇게 개선하면 여기서 member의 값을 건들 필요가 없어지니 로직이 간단해질 것 같아요.

2023-07-14 15:44 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentService.java
> +    }
저도 어제 똑같이 받은 리뷰인데 😰😰 만약 신고 당한 댓글이 삭제되면 어떻게 될까요?? 댓글 삭제 이벤트도 전파해주는게 좋아보여요

2023-07-14 15:44 UTC, jung-woo-kim commented on src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
> +        CommentSaveRequest saveRequest = new CommentSaveRequest("여길 왜 가냐");
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-07-14 16:31 UTC, Ji-soo708 commented on src/main/java/mocacong/server/dto/response/CafeImageSaveResponse.java
맞아요. 저도 응답에 일일이 추가하면서 refreshToken 구현되면 꼭 바꿔야겠다고 생각이 들더라고요 🥲

2023-07-14 16:32 UTC, Ji-soo708 commented on src/main/java/mocacong/server/exception/badrequest/InvalidReportReasonException.java
> +        super("신고 사유 정보가 올바르지 않습니다.", 6000);
신고 관련은 7000번대로 옮기겠습니다~

2023-07-14 16:36 UTC, Ji-soo708 commented on src/main/java/mocacong/server/exception/badrequest/InvalidReportReasonException.java
> +        super("신고 사유 정보가 올바르지 않습니다.", 6000);
아 혹시 좋아요를 7000번대로 옮기셨나요??

2023-07-17 14:58 UTC, kth990303 reviewed
저는 객체 책임 위주의 리뷰 남겨봤습니다~
지나가다가 들린거라 그냥 코멘트로 남길게요

2023-07-17 14:58 UTC, kth990303 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-quartz'
혹시 요거 어디에 쓰이는지 알수있을까요? 따로 import된 곳은 없어 보여서 궁금해서 코멘트 남겨요

2023-07-17 14:58 UTC, kth990303 commented on src/main/java/mocacong/server/config/BatchConfig.java
> +        if (inactiveMembersOptional.isPresent()) {
`findByStatus` 쿼리가 여기에서만 사용되고, Optional 상황에서 항상 isPresent()로 꺼낸다면 굳이 Optional 반환을 안해도 괜찮아보여요~

2023-07-17 14:58 UTC, kth990303 commented on src/main/java/mocacong/server/config/BatchConfig.java
> +                LocalDate modifiedDate = modifiedTime.toLocalDate();
`toLocalDate()`를 바로 하지 않고 `toLocalDateTime()`을 한 후에 다시 `toLocalDate()`를 한 이유가 있을까요?

2023-07-17 14:58 UTC, kth990303 commented on src/main/java/mocacong/server/config/BatchConfig.java
> +    }
저도 비즈니스 로직이 config 패키지에 있는 건 책임에 벗어난 느낌이 강하게 들어서... 서비스에 있으면 더 좋을듯합니다

2023-07-17 14:58 UTC, kth990303 commented on src/main/java/mocacong/server/service/CommentService.java
> +            if (comment.getMember() == null && comment.getReportsCount() >= 5) {
Comment 객체의 값을 꺼내기보단, 메시지를 던지는 건 어떨까요?
(comment에서 멤버 값을 꺼내서 null인지 서비스에서 체크 -> comment야 너 멤버값 가지고 있니? comment: 아니요! )

getReportsCount도 마찬가지입니다.
코멘트 도메인 자체에서 관리한다면 이 코멘트가 신고대상인지 아닌지도 코멘트 자체에서 바로 반환가능하겠네요

2023-07-17 14:58 UTC, kth990303 commented on src/main/java/mocacong/server/service/CommentService.java
> +    }
저는 로컬에서 테스트할 때 삭제 자체는 무리 없이 진행되긴 했어요.
`orphanRemoval = true`여서 SQL로 직접 삭제시키지 않는 한 괜찮을 것 같긴 한데, 한번 더 로컬에서 진행해보시겠어요? (다만 Entity 연관관계가 바뀌게 된다면 보장할 수는 없네요)

2023-07-17 14:58 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Member.java
> +        this.reportCount = reportCount;
부생성자로 중복 코드를 많이 줄일 수 있어보여요~

2023-07-17 14:58 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Comment.java
> +    }
이 정도 로직이면 도메인에서의 테스트도 있어야 될 것 같아요.
개인적으로는 예외로직 + Comment 책임과 조금 거리가 있는 ReportReason 파악 로직도 있어서 비즈니스(서비스) 로직이라 생각되기도 해요

2023-07-18 07:46 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/CommentController.java
> +    }
저걸 구현할 때는 신고기능이 코멘트에만 적용될 거라 생각하여 코멘트 api uri를 다 통일하기 위해 mapId도 포함시켰습니다. 하지만 앞으로 게시글 신고도 추가될 거 생각하면 신고 컨트롤러를 생성하는 게 좋을 거 같아 베어님 코멘트대로 commentId만 받도록 하겠습니다~

2023-07-18 08:47 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CommentService.java
> +            }
`reportCount 컬럼 삭제하고 쿼리로 유저가 신고 당한 횟수 세는게 좋아보여요.` 이 부분이 이해가 잘 안돼요. 아마 Member 엔티티의 reportCount 컬럼을 삭제하란 뜻인 거 같은데 사용자의 reportCount는 따로 보관해두는 게 맞지 않나요??

2023-07-18 08:49 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CommentService.java
> +    }
케이님 코멘트대로 해당 부분 로컬에서 테스트했을 때 이상이 없어서 그대로 올린 건데 혹시 다시 확인 가능하신가요?

2023-07-18 08:50 UTC, Ji-soo708 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-quartz'
스케줄링 작업을 위해 추가해놨던 건데 현재 코드에서는 쓰이는 곳이 없어서 삭제해야겠네요. 발견해주셔서 감사합니다!

2023-07-18 08:54 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/BatchConfig.java
> +                LocalDate modifiedDate = modifiedTime.toLocalDate();
해당 부분 로컬에서 테스트하면서 삽질하다가 필요없는 변환 코드가 들어갔는데 제가 캐치를 못한 거 같네요. 발견해주셔서 감사합니다!

2023-07-18 08:57 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/BatchConfig.java
> +                LocalDate modifiedDate = modifiedTime.toLocalDate();
바로 `toLocalDate()` 를 하면 `Cannot resolve method 'toLocalDate' in 'Timestamp'` 문제때문에 저렇게 작성했습니다. 하지만 두 줄에 거쳐서 작성할 필요는 없어보여서 수정하겠습니다.

2023-07-18 12:22 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentService.java
> +            }
사용자의 reportCount는 쿼리문으로 구할 수 있어서 굳이 컬럼을 하나 더 생성해서 관리할 필요가 없다고 느꼈어요.

2023-07-18 12:27 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CommentService.java
> +    }
앗 제가 양방향 연관관계를 끊는다고 생각하고 리뷰 남겼네요! 양방향 연관관계가 끊겼을 때 이벤트 전파가 필요할 것 같아요.

2023-07-19 13:21 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Comment.java
> +    }
케이님 코멘트 보고 생각해보니 어차피 나중에 코멘트 외에도 사진, 게시글에 대해서도 신고 기능을 추가할 거고 이 때문에 ReportService를 만들어서 여기에 신고로직을 다 옮겼습니다. 그래서 해당 부분도 ReportService로 옮겼습니다!

2023-07-19 13:24 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Member.java
> +        this.reportCount = reportCount;
코드 보다가 필요없는 생성자를 발견해 해당 생성자는 삭제했습니다..ㅎㅎ 그 후에 부생성자 고려하려 했는데 `fix: 사용하지 않는 Member 생성자 삭제` 기준으로 더이상 부생성자로 수정할 부분이 없다고 생각하여 그대로 push했는데 아니라면 코멘트 남겨주세요!

2023-07-20 06:33 UTC, jung-woo-kim commented on src/main/java/mocacong/server/repository/MemberRepository.java
> +
미사용 메서드 같아요!

2023-07-20 06:33 UTC, jung-woo-kim commented on src/main/java/mocacong/server/repository/MemberRepository.java
> +                          @Param("thresholdDateTime") Date thresholdDateTime);
벌크연산 좋습니다. 다만 where문에 있는 컬럼들이 인덱스가 아니다보니 update시에 테이블 풀 스캔이 일어나서 모든 레코드에 lock이 걸릴 가능성이 있어보이긴 해요. 쿼리 동시 수행 테스트가 필요해보이네요.

2023-07-23 09:10 UTC, jung-woo-kim approved these changes
대공사였던 것 같은데 고생하셨네요! 테스트 통과되는 것 확인했고 스웨거로 동작확인했습니다.
develop merge 하기 전에 rds 테이블 생성해주세요!
짧은 코멘트만 남겼으니 확인 부탁드려요!
고생하셨어요.

2023-07-23 16:31 UTC, merged