refact: Kakao OAuth 로직을 카카오 access token으로 인증받도록 수정
mocacong/Mocacong-Backend pull request #135
Opened 2023-09-19 03:42 UTC by Ji-soo708

## 개요
- 프론트에서 카카오 로그인을 웹뷰에서 sdk 구현으로 수정하기로 해서 서버에서도 그에 맞춰 인가코드로 사용자 인증을 받던 기존 로직을 카카오에서 발급해주는 액세스 토큰으로 인증 받도록 수정했습니다

## 작업사항
- 사용자 인증 로직을 카카오 액세스 토큰으로 인증 받도록 수정
- 사용하지 않는 메서드에 대해 기존 파일 및 테스트 코드 삭제

## 주의사항
- 안드로이드 프론트와 테스트하여 정상 동작하는 거까지 확인했습니다

2023-09-19 03:44 UTC, Ji-soo708 commented on src/main/java/mocacong/server/dto/request/KakaoLoginRequest.java
> +    private String token;
이제 인가코드 대신 카카오 액세스 토큰으로 사용자 인증을 받으므로 token으로 변경했습니다

2023-09-19 03:44 UTC, Ji-soo708 commented on src/main/resources/application-dev.yml
> -  kakao:
sdk 구현에서는 사용하지 않는 환경변수입니다

2023-09-21 12:40 UTC, kth990303 requested changes
수고하셨습니다~
코멘트 확인해주시고 바뀌는 점 없으면 그냥 안바꾸고 다시 리뷰요청 주세요!

2023-09-21 12:40 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
> +        KakaoUser user = kakaoUserClient.getUser(kakaoUserRequest, AUTHORIZATION_BEARER + token);
[카카오 SDK](https://developers.kakao.com/docs/latest/ko/kakaologin/android)를 이용하면 안드로이드 (클라이언트) 측에서 email을 얻어서 저희한테 넘겨줄 수 있을까요?

현재 로직은 아래 같은데요
```
안드 측에서 정보 확인 -> 우리 쪽에게 토큰 넘겨줌 -> 카카오 서버로 찔러서 이메일 얻어옴 -> memberRepository.findByEmail()
```

이를 아래처럼 개선할 수 있지 않을까 싶어서요
```
안드 측에서 정보 확인 -> 우리 쪽에게 이메일 넘겨줌 memberRepository.findByEmail()
```

혹시나 안드 측에서 이메일까지 얻어와서 우리쪽에 넘겨주면 우리는 feign 통신을 하지 않을 수 있어서 더 좋을 거 같아 코멘트 남겨봅니다

2023-09-21 12:56 UTC, ddiyooong commented on src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
> +        KakaoUser user = kakaoUserClient.getUser(kakaoUserRequest, AUTHORIZATION_BEARER + token);
Email 전송 가능합니다! 보안상으로도 토큰 넘겨주는 것보다 더 좋을 것 같네요

2023-09-21 13:05 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
> +        KakaoUser user = kakaoUserClient.getUser(kakaoUserRequest, AUTHORIZATION_BEARER + token);
@ddiyooong 맞아요, 현재 로직 상 이메일로 회원 식별을 하고 있다보니 가능하면 변경해주시면 좋을듯해요~

근데 사실 이메일로 회원식별 자체가 [비권장](https://mocacong.slack.com/archives/C04SGLLG2MC/p1688627935417739)이긴 한데, 이후에 고쳐지면 그때 또 변경해주시는 것도 좋을거같고... 한번 잘 결정해주시면 좋을거같아요

2023-10-22 04:17 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
> +        KakaoUser user = kakaoUserClient.getUser(kakaoUserRequest, AUTHORIZATION_BEARER + token);
시험 기간과 졸프 개발 기간과 겹쳐서 지금에서야 확인했네요😅 코멘트 남겨주신 거 보니 굳이 feign 안하고 로그인 처리하는 게 더 좋을 거 같네요! 반영해서 수정하겠습니다.

2023-11-13 08:14 UTC, Ji-soo708 reviewed
feign 통신이 빠지니 코드 양이 확 줄어드네요. 👍

2023-11-13 08:14 UTC, Ji-soo708 commented on src/main/java/mocacong/server/dto/request/KakaoLoginRequest.java
> +    private String platformId;
케이님이 남겨주신 코멘트 보고 프론트에서 받은 email과 platformId를 가지고 memberRepository에서 사용자를 찾도록 로직을 수정했습니다.

2023-11-13 09:15 UTC, kth990303 approved these changes
잘 제거해주신 거 같아 크게 남길 말이 없네요 ㅎㅎ
수고하셨습니다

2023-11-13 09:17 UTC, merged