feat: 마이페이지 회원 작성 댓글 목록 조회 시, 카페 별로 필터링되도록 구현
mocacong/Mocacong-Backend pull request #136
Opened 2023-11-11 07:34 UTC by kth990303

## 개요
- 현재 마이페이지에서 회원이 작성한 댓글 목록을 조회할 경우, 별다른 정렬 순서 없이 댓글 목록을 보여주고 있습니다.
- 이에 따라, 카페 별로 필터링하여 조회할 수 있도록 API Spec이 아래와 같이 댓글 목록을 list로 받도록 변경됐습니다.
<img width="212" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/565f297d-1782-4788-913a-a5035832cde0">

## 작업사항
- 필터링되도록 작업.

## 주의사항
- TODO 에도 적어놨지만, 댓글 목록을 카페 별로 필터링하기 위해 DB에서 전체를 find하도록 작업했습니다. 
  - 카페 종류 수에 따라 페이지네이션할지, 댓글 개수에 따라 페이지네이션할지 협의가 필요합니다. 
  - 댓글 개수에 따라 페이지네이션한다면? 상위 DTO(`List<MyCommentCafeResponse`)의 사이즈는 고려하지 않고, 하위 DTO (`List<String> comments`)의 사이즈는 count 개수만큼이 되도록 해야 하는데, 이 역시 Slice로 하기 힘들어보였습니다. Slice로 할 경우 상위 DTO(`List<MyCommentCafeResponse`) 개수만큼 슬라이싱되기 때문.
  - 따라서 우선은 카페 종류 수대로 페이지네이션했습니다. (카페 25군데, 댓글 80개 작성했을 경우 -> page(0, 5) 시에 카페 5군데에 작성한 댓글 전체를 보여줌.)
    - 관련 스레드: https://mocacong.slack.com/archives/C04SGLLG2MC/p1699671506353769?thread_ts=1699615459.688409&cid=C04SGLLG2MC
  
- DB에서 native query로 new map으로 필터링처리를 하게 해버리게 쿼리를 짜보려 했는데, map은 중복 key 허용을 안해서 어려웠고 또  querydsl 적용하지 않고는 매우 복잡할 거 같아 애플리케이션 단에서 작업했어요.

- 더 좋은 방안 있으면 리뷰 부탁드려요!

2023-11-12 02:09 UTC, jung-woo-kim requested changes
역시 로직이 조금만 복잡해져도 구현이 힘들어지는군요 😓
개인적으로 실무에서도 위와 비슷한 상황을 맞다뜨렸었는데 결국 jpa 페이지네이션을 위해 한방 쿼리로 위 문제를 해결했던 것 같아요.

결국 장기적으로는 query dsl을 사용하는 것이 좋아보이네요,,

로직은 현재 최선인 것 같고, 엔티티 equals 비교 관련해서 개선점이 보여서 rc 날려요!
확인 부탁드립니다~

2023-11-12 02:09 UTC, jung-woo-kim commented on src/main/java/mocacong/server/domain/Cafe.java
> +        }
엔티티에서 프록시 객체 비교 시 위에서 false를 반환하게 될 것 같아요.
instanceOf를 사용하는건 어떤가요?

[참고하면 좋은 곳](https://www.inflearn.com/questions/333337/%ED%94%84%EB%A1%9D%EC%8B%9C-%EA%B4%80%EB%A0%A8%ED%95%9C-equals-%EC%98%A4%EB%B2%84%EB%9D%BC%EC%9D%B4%EB%94%A9-%EC%A0%9C%EA%B0%80-%EC%9D%B4%ED%95%B4%ED%95%9C-%EA%B2%83%EC%9D%B4-%EB%A7%9E%EB%82%98%EC%9A%94)

2023-11-12 10:50 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Cafe.java
> +        }
좋은 의견 감사합니다 :)
한가지만 체크되면 반영해보고 싶은데요.

instanceOf 를 사용하게 될 경우, 대칭성에 위배될 여지가 있지 않을까 싶어서요.
Cafe, ProxyCafe가 있다고 할 때, ProxyCafe instanceOf Cafe는 true이지만 Cafe instanceOf ProxyCafe 이 부분이 통과되는지 궁금해요.

실제로 Cafe DB table에서 동일 mapId가 unique key로 제약돼있고, 영속성 컨텍스트 내에 Cafe가 있다면 proxy 객체가 아닌 해당 실제객체를 조회하기 때문에 equals는 크리티컬하게 쓰이진 않을 거 같아요. 그래서 의견 바로 반영하려다가, 대칭성 관련 면이 좀 애매해서 질문드려요.

확인 후 코멘트 남겨주시면 반영 또는 반려하겠습니다.
감사합니다!

2023-11-12 10:55 UTC, kth990303 commented
1. querydsl 도입하는 부분에 대해서 찬성합니다.
실제로, querydsl 도입하면 편리성 생산성 면에서 좋다고 생각하고, 성능도 일부 상승될 여지가 있어보여요.

다만 querydsl을 따로 학습하는 비용으로 인해 개발에 차질이 생길 여지가 있다는 점에 대해서도 우려됩니다. 백엔드 팀원들 모두 동의하면 querydsl 추가하시죠!


2. 저도 DB에서 쿼리로 페이지네이션 바로 가져오는 거 좋은 거 같아요! 복잡한 로직에 많은 데이터일 경우, 애플리케이션 단에서 하니까 힙메모리가... ㄷㄷ
querydsl이 도입된다면 해당 로직 어떻게 바뀔 수 있을지 궁금해요. 실무에서 비슷한 상황에 어떻게 처리하셨나요? select 안에 List가 또 있어서 서브쿼리를 사용하셨을지, 아니면 별도 방법이 있을지 궁금해서 스포 조금 부탁드립니다!

2023-11-12 11:37 UTC, jung-woo-kim commented on src/main/java/mocacong/server/domain/Cafe.java
> +        }
아하~
일단 질문이 있는데, unique 제약 조건과 영속성 컨텍스트와 관련이 있나요?? (제가 잘몰라서,,ㅎㅎ)
프록시 객체가 나오는 상황에선 어차피 똑같다고 생각이 들어서요

instanceOf는 테스트 해보니 말씀주신 부분이 맞는것 같아요. 

다만, 제가 생각할 때 대부분의 상황에서 instanceOf가 잘 돌아갈 것이라고 생각되는 부분은 보통 Cafe equal Cafe / ProxyCafe equal ProxyCafe의 형태로 사용되기 때문이 아닐까 조심스레 예측해봅니다.

또, 그냥 getClass를 사용했을 때는 Cafe equal Cafe만 가능(ProxyCafe equal ProxyCafe 불가)한 반면 instanceOf를 사용하면 보다 여러 상황에 대응가능하게 되어서 더 적합하다고 생각이 듭니다! 

Hibernate.class를 사용하는 방법도 있다곤 하는데 Hibernate 종속이 되어버려 좋진 않은 것 같아요.

요거 메리님 의견도 좀 궁금하네요! 보시고 의견 또 달아주세요! @Ji-soo708 @kth990303

2023-11-12 11:40 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Cafe.java
> +        }
unique 제약조건과 영속성 컨텍스트는 별개로 말한거예요

1. unique 제약조건으로 인해 동일 mapid 가 들어갈 일이 없어서 equals가 쓰일 일은 없을 것 
2. 카페 동일 여부 비교 시, 보통 영속성컨텍스트 내에서 조회되므로 프록시 대신 실제 객체가 가져오므로 equals가 쓰인다 하더라도 문제될 이슈는 없음.

이렇게 별개로 얘기한거였어요.

하지만 말씀해주신 내용이 좋아보여서 적용 긍정적 고려중입니다 :)

2023-11-12 12:26 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Cafe.java
> +        }
위에서 쭉 읽고 코멘트 남깁니다~ 저도 `instanceOf`로 비교하는 방식이 더 유연한 방법인 거 같습니다. 대칭성 문제에 대해서도 얘기 나누셨는데 정우님 코멘트처럼 보통의 경우, Cafe equal Cafe / ProxyCafe equal ProxyCafe의 형태로 사용돼서 잘 돌아가면 사용하지 않을 이유가 없어보입니다~

2023-11-12 12:26 UTC, Ji-soo708 commented
> * querydsl 도입하는 부분에 대해서 찬성합니다.
>   실제로, querydsl 도입하면 편리성 생산성 면에서 좋다고 생각하고, 성능도 일부 상승될 여지가 있어보여요.
>   다만 querydsl을 따로 학습하는 비용으로 인해 개발에 차질이 생길 여지가 있다는 점에 대해서도 우려됩니다. 백엔드 팀원들 모두 동의하면 querydsl 추가하시죠!
> * 저도 DB에서 쿼리로 페이지네이션 바로 가져오는 거 좋은 거 같아요! 복잡한 로직에 많은 데이터일 경우, 애플리케이션 단에서 하니까 힙메모리가... ㄷㄷ
>   querydsl이 도입된다면 해당 로직 어떻게 바뀔 수 있을지 궁금해요. 실무에서 비슷한 상황에 어떻게 처리하셨나요? select 안에 List가 또 있어서 서브쿼리를 사용하셨을지, 아니면 별도 방법이 있을지 궁금해서 스포 조금 부탁드립니다!

2023-11-12 16:12 UTC, jung-woo-kim commented
아직 코드 리뷰 못받긴 했는데, 그냥 native query = true해서 서브쿼리로 해결했어요..ㅋㅋㅋ 메모리에 다올리긴 너무 무리같고, 결국엔 쿼리로 해결해야하는데 spring data jpa에서 join에 subquery를 사용할 수 없으니 방법이 떠오르질 않더라구요. ㅎㅎ.. 다음에 코드리뷰 받아보고 세미나로 돌아오겠습니다 :)

2023-11-29 15:44 UTC, jung-woo-kim approved these changes
변경 확인했습니다 :) 고생하셨어요!

2023-12-01 08:34 UTC, merged