feat: 마이페이지 카페 조회 시 roadAddress 및 내가 남긴 리뷰 함께 조회 기능 구현
mocacong/Mocacong-Backend pull request #137
Opened 2023-11-12 06:10 UTC by jung-woo-kim

## 개요
- 피그마 디자인 변경에 따른 마이페이지 카페 조회 시 도로명 주소를 함께 반환하는 기능을 구현했습니다.

## 작업사항
- DB 변경사항있습니다.
  - cafe 테이블  road_address(string) 컬럼 추가
  - Approve시 운영 db에 제가 추가해두겠습니다!
-  이제 cafe가 저장될 때 이미 카페가 있다면 roadAddress를 update하여 도로명 주소를 넣어줍니다.
  - 추후 배치로 도로명 주소를 넣어준다면 위 로직은 삭제해도 무방합니다.
- 외에는 새로 생성된 road_address를 함께 조회하는 기능을 구현했습니다.

## 주의사항
- Merge 전 컬럼을 추가해놔야할 것 같아서 Merge는 제가 하겠습니다!
- 오랜만에 자바를 써서..ㅎㅎ 혹시 이상한 부분 있으면 말씀해주세요!

2023-11-13 08:25 UTC, Ji-soo708 approved these changes
코드 로직 자체는 문제 없어보여서 approve 할게요. 수고하셨습니다~ 그런데 존재하는 카페에 대해 update하는 부분에서 람다식으로 간결하게 변경 가능할 거 같아 코멘트 남겼는데 확인해주시면 감사합니다 😀

2023-11-13 09:29 UTC, kth990303 requested changes
작업해주신 내용 확인완료했어요. 
작업량이 은근 많아 고생하셨을 거 같아요.

도로명 주소 업뎃하는 부분 코드가 조금 읽기 힘들었어서 코멘트로 제안드렸는데요.
확인해주시고 댓글 남겨주세요 감사합니다 👍

2023-11-13 09:29 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +            return;
람다식을 활용한다면 `ifPresentOrElse` 도 좋은 선택지일 듯 해요.

```java
@Transactional
public void save(CafeRegisterRequest request) {
    Cafe cafe = new Cafe(request.getId(), request.getName(), request.getRoadAddress());

    try {
        cafeRepository.findByMapId(request.getId())
                .ifPresentOrElse(
                        existedCafe -> existedCafe.updateCafeRoadAddress(request.getRoadAddress()),
                        () -> cafeRepository.save(cafe)
                );
    } catch (DataIntegrityViolationException e) {
        throw new DuplicateCafeException();
    }
}
```

람다식을 활용하지 않는다면 59~64번째 줄을 메서드 분리하는 게 좋아보여요.
처음에는 무슨 코드인가 했어서요..ㅎㅎ

2023-11-13 09:29 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +                        comment.getCafe().getRoadAddress()
코멘트가 작성된 카페의 정보에 대한 response를 보내줘야 할 때가 좀 있네요.
아예 DTO에 Cafe 엔티티를 받는 정적 팩터리 메서드를 만드는 것도 방법일 거 같기도 하고요...

comment의 getter + getter 디미터 법칙이 조금 걸려서 comment 엔티티에 도로명주소 반환해주는 메서드를 만들어도 될 거 같기도 하고.
조금 고민되네요. 한번 같이 생각해주시고 적절하게 반영해주세요!

2023-11-13 09:29 UTC, kth990303 commented on src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
> +    private String desk;
이거 추가된 배경이 궁금해서 코멘트 남겨요.
마이페이지에서 내가 카페에 작성한 리뷰를 보는건데, 그 카페에 대한 리뷰정보가 필요해진 이유가 추가로 있을까? 궁금해졌어요

2023-11-13 11:03 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +            return;
오 위에 처럼 변경이 가능하군요~ 확실히 이 형태가 더 보기 좋은 거 같습니다.

2023-11-26 03:08 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CafeService.java
> +            return;
이해하기 편하게 하려고 함수형 보단 절차지향으로 짜봤는데, 오히려 독이 되었군요.. 고쳐서 반영해둘게요!

2023-11-26 03:17 UTC, jung-woo-kim commented on src/main/java/mocacong/server/service/CafeService.java
> +                        comment.getCafe().getRoadAddress()
요즘 코틀린 쓰다보니까 너무 생각없이 디미터 법칙을 무시해버렸는데, 위 경우 get -> get으로 되는 경우가 ㅁ많아서 comment 엔티티에 메서드가 너무 많이 생길 수도 있을 것 같아서 우선은 from 정적 팩토리 메서드 패턴을 쓰는게 나아보여서 그렇게 변경했습니다!

2023-11-26 03:26 UTC, jung-woo-kim commented on src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
> +    private String desk;
responseBody에 roadAress / 모든 리뷰(스터디타입, 와이파이 등등) 추가

요런 요구사항이 있었어서 우선 내가 쓴 리뷰의 Cafe Detail로 반영했습니다!

2023-12-01 09:59 UTC, merged