feat: 카페 정보 조회 api 구현
mocacong/Mocacong-Backend pull request #19
Opened 2023-03-30 08:23 UTC by kth990303

## 개요
- 카페 정보 조회 api 구현

## 작업사항
- 카페 정보 조회 api를 구현했습니다.
  - 평점, 리뷰, 코멘트가 아무것도 없을 때엔, 평점은 null을 리뷰와 코멘트는 빈 객체를 보내주게 구현했습니다.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/57135043/228774932-6063fbf0-fe6b-4c92-a86f-455fd7248e1b.png">

## 주의사항
- TODO 주석이 달려있으니 한 번 확인해주세요
- api spec에 맞는지 확인해주세요.

2023-03-30 08:25 UTC, kth990303 commented on src/main/java/mocacong/server/domain/StudyType.java
> +    private Long id;
`StudyType`은 리뷰 세부정보 느낌이 아니기도 하고, 모카콩에서 해당 타입은 매우 중요한 로직이기 때문이기 때문에 별도의 생명주기를 가지도록 엔티티 구현했습니다.

2023-03-30 08:28 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +                .orElse(null);
해당 카페에 평점을 매기지 않았으면 null을 반환해주기로 결정나서 이와 같이 처리했습니다.

2023-03-31 02:12 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +    }
저도 `if-else` 문이나 `switch` 문 밖에 생각이 안나네요..
```
switch (Integer.compare(numSoloStudyTypes, numGroupStudyTypes)) {
        case 1:
            return SOLO_STUDY_TYPE;
        case -1:
            return GROUP_STUDY_TYPE;
        default:
            return BOTH_STUDY_TYPE;
    }
```
`if-else` 는 케이님이 작성하신 코드보다 별로여서 `switch` 문 코드 제시할게요

2023-03-31 06:25 UTC, Ji-soo708 requested changes
api 스펙에 맞게 잘 작성해주셔서 딱히 리뷰 남길 게 없네요.. 수고하셨습니다😊

2023-03-31 06:25 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +    // TODO: 리뷰, 코멘트 기능 추가되면 조회 테스트 추가할 것
이미 등록된 카페는 새로 등록 안되는지 확인하는 테스트는 생략해도 될까요?

2023-03-31 06:49 UTC, kth990303 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +    // TODO: 리뷰, 코멘트 기능 추가되면 조회 테스트 추가할 것
해당 테스트는 41~52번째 라인에 이미 존재합니다!
```java
    @Test
    @DisplayName("등록되어 있는 카페는 등록하지 않는다")
    void cafeSaveDuplicate() {
        CafeRegisterRequest request1 = new CafeRegisterRequest("20", "메리네 카페");
        cafeService.save(request1);

        CafeRegisterRequest request2 = new CafeRegisterRequest("20", "카페");
        cafeService.save(request2);

        List<Cafe> actual = cafeRepository.findAll();
        assertThat(actual).hasSize(1);
    }
```

2023-03-31 06:50 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +    }
이 부분은 일단 if문으로 유지하려고 합니다!

2023-03-31 06:54 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +    // TODO: 리뷰, 코멘트 기능 추가되면 조회 테스트 추가할 것
그 부분을 못봤나보네요. 죄송합니다 😢 바로 approve 하겠습니다!

2023-03-31 06:55 UTC, Ji-soo708 approved these changes

2023-03-31 07:42 UTC, merged