feat: 카페에 대한 리뷰 수정 api 구현
mocacong/Mocacong-Backend pull request #24
Opened 2023-04-01 08:52 UTC by Ji-soo708

## 개요
- 카페에 대한 리뷰(세부정보, 평점, 카페 스터디타입)를 수정하는 api를 구현했습니다.

## 작업사항
- 카페 리뷰 수정 비즈니스 로직 및 api를 구현했습니다.
  - 카페 리뷰 등록과 마찬가지로 세부정보, 평점, 카페 스터디타입 모두를 한번에 수정하도록 처리했습니다. 
  - 등록한 적이 있는 리뷰에 한해서만 리뷰 수정이 가능하도록 처리했습니다. 

## 주의사항
- api 스펙과 동일하게 구현됐는지 확인해주세요
- 기획과 달리 잘못 구현된 로직이 있는지 확인해주세요
- 누락된 테스트코드가 있는지 확인해주세요

2023-04-01 08:58 UTC, Ji-soo708 commented on src/main/java/mocacong/server/exception/notfound/NotFoundReviewException.java
> +        super("해당 카페에 기여한 평점이 존재하지 않습니다.", 2006);
컨플루언스에 적힌 예외 메시지대로 적었는데 리뷰를 수정할 때 평점과 세부사항, 스터디 타입 모두 다 수정하기로 바꿔서 커스텀 예외 메시지를 바꿔야 하지 않을까 싶네요

2023-04-01 08:58 UTC, Ji-soo708 commented on src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
> +    }
테스트는 정상적으로 수정한 경우/등록하지 않은 리뷰에 대해 수정하면 예외를 던지는 경우 이렇게 2가지 작성했습니다

2023-04-01 08:58 UTC, Ji-soo708 commented on src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
> +    public static ExtractableResponse<Response> 카페_리뷰_수정(String token, String mapId, CafeReviewRequest request) {
`카페_리뷰_수정` 메서드는 추가했으나 아직 테스트 코드에서 사용하지 않습니다

2023-04-01 09:06 UTC, kth990303 requested changes
수고하셨어요~ 테스트 코드는 완벽해보입니다 :)
프로덕션 코드에서 불필요한 로직이나 위험해보이는 코드들이 좀 보여서 RC로 남겼습니다.

2023-04-01 09:06 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        score.setScore(request.getMyScore());
lombok의 `@Setter`는 최대한 지양하는 것이 좋다고 생각해요.
변경하면 안되는 필드에 대해서도 다 setter를 public하게 열어버리기도 하고, 변경 관련된 도메인 로직은 나름 중요한 부분이라 생각되기 때문이에요. 이는 객체지향 캡슐화와 은닉화 부분에도 관련이 있을 거 같아요.

도메인에 갱신로직을 만들고 테스트 코드를 짜는건 어떤가요?

2023-04-01 09:06 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        reviewRepository.save(review);
여기부분도 모두 마찬가지입니다!

2023-04-01 09:06 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +    public CafeReviewResponse updateCafeReview(String email, String mapId, CafeReviewRequest request) {
리뷰 등록 request, response dto를 재활용한 것 같은데, 만약 등록 api 명세가 달라진다면? 등록 api만 수정해도 될텐데 수정 api spec까지 변경돼서 의존성이 커지고 변경에 유연하지 못할 듯 해요. 

카페 리뷰 수정 dto들을 따로 생성하는 건 어떤가요?

2023-04-01 09:09 UTC, kth990303 commented on src/main/java/mocacong/server/exception/notfound/NotFoundReviewException.java
> +        super("해당 카페에 기여한 평점이 존재하지 않습니다.", 2006);
3008번 예외코드는 어떤가요?
`3008: 존재하지 않는 리뷰입니다.`

2023-04-01 09:15 UTC, Ji-soo708 commented on src/main/java/mocacong/server/exception/notfound/NotFoundReviewException.java
> +        super("해당 카페에 기여한 평점이 존재하지 않습니다.", 2006);
아 `3008` 이 있는 지 못봤네요. 바로 수정하겠습니다. 감사합니다!

2023-04-01 09:23 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        }
그렇게 바꿨습니다! 훨씬 보기 좋네요👍

2023-04-01 09:33 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        score.setScore(request.getMyScore());
`@Setter` 없애고 각 도메인에 메서드 추가했습니다!

2023-04-01 09:35 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        scoreRepository.save(score);
그렇게만 해도 갱신된다는 건 지금 알았네요! 지적 감사합니다~ 👍

2023-04-01 09:44 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +    public CafeReviewResponse updateCafeReview(String email, String mapId, CafeReviewRequest request) {
넵 좋습니다! 따로 생성하겠습니다~

2023-04-01 09:59 UTC, kth990303 requested changes
setter 로직이 (사실상) 전이랑 같아서 조금 더 리뷰남겼습니다!

2023-04-01 09:59 UTC, kth990303 commented on src/main/java/mocacong/server/domain/CafeDetail.java
> +    public void setWifi(Wifi wifi) {
변경 로직을 setter를 이용하지 말고 생성자를 최대한 활용해보는건 어때요? 사실상 lombok setter쓴거나 다름없어보여요! 다른 메서드도 모두 마찬가지입니다~

2023-04-01 09:59 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Score.java
> +        this.score = myScore;
이 경우처럼 vo가 아닌 entity의 경우 jpa 변경감지를 위해 setter를 이용하곤 하는데요. 이런경우는 항상 유효성 체크가 누락되지 않는지 조심해야 합니다! 지금은 범위를 벗어난 평점이 들어가겠네요.

이런 누락되는 경우때문에 setter는 테스트 코드를 짜주는 것이 좋습니다

2023-04-01 09:59 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        studyType.setStudyTypeValue(request.getMyStudyType());
이 부분들이 생성자를 이용하면 훨씬 나아질거같네요

2023-04-01 09:59 UTC, kth990303 commented on src/main/java/mocacong/server/repository/ScoreRepository.java
> +    Score findByMemberAndCafe(Member member, Cafe cafe);
사실상 위 메서드랑 역할이 같은데 만드신 이유가 있을까요?

2023-04-02 07:12 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Score.java
> +        this.score = myScore;
`setScore` 는 수정 기능을 다 생성자로 변경하는 과정에서 지웠는데 추가해야 할까요?

2023-04-02 07:13 UTC, Ji-soo708 commented on src/main/java/mocacong/server/repository/ScoreRepository.java
> +    Score findByMemberAndCafe(Member member, Cafe cafe);
구현하다가 새 메서드를 만든 거 같은데 코드 수정하면서 사용하지 않게 돼서 지우겠습니다!

2023-04-02 07:23 UTC, Ji-soo708 reviewed
`setter` 관련 코드 삭제하고 생성자로 수정하는 코드를 추가했습니다! 항상 코드리뷰 감사합니다 👍

2023-04-02 07:23 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Cafe.java
> +    public void removeScore(Score score) {
`score` 를 생성자로 값 수정하는 과정에서 기존 객체를 지우고 다시 `score` 를 생성해야 한다고 생각해서 추가했습니다.

2023-04-02 07:23 UTC, Ji-soo708 commented on src/main/java/mocacong/server/repository/ScoreRepository.java
> -    Score findByMemberAndCafe(Member member, Cafe cafe);
필요없는 메서드 제거했습니다

2023-04-02 07:23 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        String newStudyTypeValue = request.getMyStudyType();
`setter` 대신 생성자로 수정했습니다

2023-04-02 07:23 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        CafeReviewUpdateRequest request = new CafeReviewUpdateRequest(5, "group", "빵빵해요", "여유로워요",
리뷰수정 기능을 `setter` 대신 생성자로 수정하면서 테스트 안에서 `studyType` 까지 수정된 결과로 잘 반영됐는지 확인하기 위해 `solo` 에서 `group` 으로 변경했습니다

2023-04-02 09:33 UTC, kth990303 requested changes
수고하셨어요.
버그 존재, Entity와 VO에 따른 setter 메서드 관점 차이 때문에 RC로 남깁니다.

CafeDetail에서 cafeDetail.setXXX, setXXX, setXXX 이러한 부분이 문제가 되는것이지, 엔티티에서 setter를 쓰지말라! 는 아닙니다. 그럼에도 불구하고 lombok의 `@Setter`는 막는 편입니다. 만약 A Entity의 name만 setter가 있으면 좋겠는데, lombok의 `@Setter`를 쓴다면? name뿐만 아니라 A Entity의 모든 필드에 setter 메서드가 열려서 굉장히 위험해질 수 있습니다.

2023-04-02 09:33 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        studyType = new StudyType(studyType.getMember(), studyType.getCafe(), newStudyTypeValue);
현재 메리가 작성한 로직은 아래와 같아요.
1. `review.getStudyType()`으로 현재 리뷰의 studyType을 꺼낸다.
2. 요청으로 들어온 새로운 studyType을 생성한다.

저장하지 않은 이유는 cascade 옵션을 고려해서 한 걸까요 아니면 실수일까요? 결론적으론 저장을 하지 않아도 작동합니다! JPA cascade 옵션 덕분이에요.
```java
    @OneToMany(mappedBy = "cafe", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private List<StudyType> studyTypes;
```
하지만 여기서 cafe.addStudyType(studyType); 작업을 추가로 해주지 않으면 studyType으로 저장은 되지만 연관관계로 cafe의 studyTypes List에는 존재하지 않게됩니다. 주의해주세요!

이 부분도 문제긴 하지만, 조금 더 심각한 문제가 존재합니다. 바로 현재 로직은 studyType을 *수정*하는 작업이 아닌, *새롭게 저장하는 역할*이라는게 문제입니다!
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/57135043/229343095-a0573519-6b61-4504-9396-4d817f79461d.png">

JPA의 변경감지는 **새로 생성된 객체 대상이 아닌, 원래 있던 엔티티에 변경이 가해졌을 때 발생**합니다. 그렇기 때문에 리뷰에 남겼듯이, 생명주기를 가지지 않는 VO와 달리 생명주기를 가지는 Entity는 setter(또는 값을 바꾸는 어떠한 메서드)를 피할 수는 없어요. CafeDetail에 일일이 setter를 하지 말고 생성자로 만들라는 이유는 CafeDetail은 Entity가 아닌 VO이기 때문이에요. Entity와 VO의 차이점은 별도로 공부하시는 걸 추천드릴게요!

CafeDetail의 경우도 잘 생각해보시면 `cafeDetail = new CafeDetail(...)` 로 생성자를 통해 새로운 값을 만들지만 결국 `updateCafeDetail(cafeDetail)`로 setter 작업을 하고 있는 것이므로 사실상 setter를 피하는 것은 불가피해요. 무분별한 setter는 막아야겠지만 요구사항으로 주어지는 setter는 필요하다고 생각해요.

그 외에도 Review 객체에게 studyType을 변경해달라고 메시지를 보내지 않고 ,studyType 값을 꺼내서 변경해버리는 것은 Review 객체에게 주어진 책임을 지키게 하지 않고, 무작위로 진행해버리는 듯한 느낌도 있어요. 즉, 객체지향과는 조금 거리가 있는 로직이라 생각됩니다.
아래와 같이 로직을 바꿔보는건 어때요?
1. review 객체에게 request.getMyStudyType() 값을 전달해주면서 update해줘~ 라고 메시지를 던진다
```suggestion
        review.updateStudyType(request.getMyStudyType());
```
2. review에 있는 studyType 객체한테 studyType 이걸로 바꿔줘~ 라고 메시지를 보낸다.
```java
// Review 객체에 있는 로직
public void updateStudyType(String studyType) {
    this.studyType.updateStudyTypeValue(studyType);
}
```

3. StudyType 객체에서 해당 값을 변경한다.
```java
// StudyType 객체에 추가한 메서드
    public void updateStudyTypeValue(String studyTypeValue) {
        String lowerCaseStudyTypeValue = studyTypeValue.toLowerCase();
        validateValue(lowerCaseStudyTypeValue);
        this.studyTypeValue = lowerCaseStudyTypeValue;
    }
``` 

위와 같이 작성하면 테스트는 통과합니다. 불필요하게 새로운 객체를 생성하는 비용도 없앨 수 있습니다.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/57135043/229343315-e0f6fa9a-d4c8-47ef-8fd3-14bd42294b44.png">

2023-04-02 09:33 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        Score newScore = new Score(request.getMyScore(), member, cafe);
여기서도 JPA의 변경감지를 이용해보는 것은 어떤가요? 참고로 Score도 VO가 아닌 Entity입니다!

2023-04-02 09:33 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        review.updateReview(updatedCafeDetail);
164~171번째 줄에서 new CafeDetail을 만들어주었는데 173번째 줄의 `updateReview`의 ***Review 엔티티*** 메서드에서 new CafeDetail을 또 해준 이유가 있나요?

2023-04-02 09:33 UTC, kth990303 commented on src/test/java/mocacong/server/domain/CafeTest.java
> +
이 공백은 불필요해보이는데 지워도 괜찮을 듯해요!

2023-04-02 09:33 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Cafe.java
> +    public void removeScore(Score score) {
score는 Entity이기 때문에 기존 방식대로 updateScore 또는 setScore이 나아보여요

2023-04-02 09:33 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Score.java
> +    }
이 부분도 없어져도 되겠네요.
참고로 평점은 지워질 일이 현재 기획상에선 아예 없다고 생각합니다! 회원이 탈퇴해도 평점은 남아있어야 하니..

2023-04-02 10:24 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +                        "깨끗해요", "충분해요", "조용해요", "불편해요"));
테스트 코드를 잘못 작성한 걸 지금 알았네요... update 한 번만 해서 통과하도록 하겠습니다! 지적 감사합니다

2023-04-02 10:33 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        studyType = new StudyType(studyType.getMember(), studyType.getCafe(), newStudyTypeValue);
확인했습니다! 제가 완전히 다르게 이해하고 구현했었네요,,,😢😢 친절한 설명 덕분에 어딜 고쳐야 할지 잘 알겠어요! VO랑 Entity 부분은 제가 더 공부하고 나중에 트러블슈팅에 정리해야겠네요. 설명과 지적 감사합니다!👍

2023-04-02 10:34 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        review.updateReview(updatedCafeDetail);
제가 놓치고 수정 안 한 거 같습니다.. 수정해서 다시 올리겠습니다! 지적 감사합니다~

2023-04-02 10:35 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Score.java
> +    }
관련 코드는 다 삭제하겠습니다!

2023-04-02 10:35 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        Score newScore = new Score(request.getMyScore(), member, cafe);
앞에서 적으신 글 참고해서 수정하겠습니다!

2023-04-02 10:58 UTC, kth990303 approved these changes
수고하셨어요~ 몇 가지 코멘트 남겨드렸고, Git 충돌해결하시면 될 거 같아요.
git 충돌 부담스러우시면 슬랙 DM 주시면 제가 해결하고 머지할게요~

2023-04-02 10:58 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        );
null이 들어올 경우 internal servere error가 터지겠네요 이전 코드 참고해서 추가부탁드려요!

2023-04-02 10:58 UTC, kth990303 commented on src/main/java/mocacong/server/domain/StudyType.java
> +    }
update 시에도 검증이 잘 되는지 테스트 코드 있음 좋을 거 같아요

2023-04-02 10:58 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Score.java
> +    }
여기도 범위 검증 잘 되는지 테스트 코드!

2023-04-02 11:20 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        );
해당 코드 수정하겠습니다!

2023-04-02 11:31 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/StudyType.java
> +    }
도메인 테스트에 추가하겠습니다!

2023-04-02 11:41 UTC, merged