feat: OAuth Apple 로그인 api 구현
mocacong/Mocacong-Backend pull request #34
Opened 2023-04-12 11:05 UTC by kth990303

## 개요
- 애플 OAuth 로그인 기능을 FeignClient를 이용하여 구현했습니다.

## 작업사항
- OAuth 사용자 프로세스의 큰 틀은 아래와 같습니다.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/57135043/231438768-8b8719fc-3e28-453f-9d6e-dbf636de64af.png">
- Apple OAuth 동작 원리 및 코드에 대해서는 컨플루언스 위키를 참고해주세요
- 추가된 로그인 및 회원가입 API spec 에 맞춰서 구현했습니다.

## 주의사항
- 보안 상 문제되는 코드가 있다면 리뷰해주세요
- 누락된 테스트 코드가 있는지 확인해주세요
- 불필요한 로직이나 추가돼야 할 로직이 있다면 리뷰해주세요
- 오타가 있는지 확인해주세요

2023-04-14 15:21 UTC, Ji-soo708 requested changes
코드 잘 봤습니다. 추가된 파일 수부터가 정말 어려운 구현이었다는 게 눈에 보이네요🥲 코드 보면서 코멘트들을 달았는데 테스트 코멘트 같은 경우는 제가 검토는 했지만 이미 작성된 테스트(혹은 이미 작성된 유사한 테스트)를 요청했을 수 있어서 이 부분 감안해서 봐주시면 감사합니다. 수고하셨어요!

2023-04-14 15:21 UTC, Ji-soo708 commented on src/test/java/mocacong/server/security/auth/apple/AppleOAuthUserProviderTest.java
> +class AppleOAuthUserProviderTest {
올바른 공개키랑 잘못된 공개키를 각각 생성하고 `AppleOAuthUserProvider` 에서 조회했을 때, 예상과 다른 결과가 반환되는지 확인하는 건 `AppleJwtParserTest` 에서 비슷한 작업을 해서 필요없을까요?

2023-04-14 15:21 UTC, Ji-soo708 commented on src/test/java/mocacong/server/security/auth/apple/ApplePublicKeysTest.java
> +class ApplePublicKeysTest {
`ApplePublicKey` 객체에서 kty, kid, alg, n, e 등의 속성이 제대로 저장되어 있는지 확인하는 테스트랑 생성자에서 `keys` 리스트 값을 변경 시도해서 불변성 한번 더 체크하는 테스트 있음 좋겠습니다.

2023-04-14 15:32 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/apple/AppleOAuthUserProvider.java
> +}
identityToken 값을 검증하는 역할이 `AppleJwtParser`의 parseHeaders 메서드에서 해주고 있다고 생각해요. 올바르지 않은 identityToken이면 `JsonProcessingException` 또는 `ArrayIndexOutOfBoundsException`이 발생하여 1015번 에러를 반환합니다. 실제로 프론트와 통신 시에 해당 에러 반환 덕분에 identityToken을 검증한 사례가 있어서 AppleJwtParser, AppleJwtParserTest로 충분하다고 생각이 들어요 :)

추가로, `parsePublicKeyAndGetClaims` 메서드에서 추가로 JWT 검증을, `AppleClaimsValidator`에서 claim 검증을 해주고 있습니다.

2023-04-14 15:33 UTC, kth990303 commented on src/main/java/mocacong/server/dto/request/OAuthMemberSignUpRequest.java
> +    private String email;
추가로 적어보자면 apple oauth에서는 사용자가 이메일 제공을 동의하지 않으면 private email을 보내준다고 해요.

만약 적용이 필요한 요구사항이었다 하더라도 `@Email`로 검증이 충분할지도 의문이 들기도 합니다

2023-04-14 15:44 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/apple/PublicKeyGenerator.java
> +    public PublicKey generatePublicKey(Map<String, String> headers, ApplePublicKeys applePublicKeys) {
굉장히 좋은 리뷰라 생각이 들어서 애플 서버 내에서 공개키 정보 구성요소들의 바뀌는 주기를 한 번 조사해봤는데, 공식 홈페이지에도 공식 스레드에도 언급이 없네요... 혹시 자료 찾게 되신다면 코멘트 부탁드려요.

확실히 public key를 위해 애플 서버와 통신하는 데에는 시간이 많이 듭니다. 마음 같아서는 스프링 스케줄러를 이용하여 적정 주기마다 이용하고, 그 외에는 캐싱을 해두고 싶네요.

캐싱 방법이 조금 고민이 되는데 생각나는 방안은 아래와 같습니다.
1. concurrentHashMap을 이용한 local cache
2. DB에 저장
3. AWS Elasticache를 이용한 Redis에 저장

이 부분은 일단 코멘트로 남겨두고, 다음 주 회의 때 조금 얘기해보는 것도 괜찮을 거 같아요.
애플의 공개키 구성요소 정보들이 바뀌는 주기에 대한 신뢰성있는 자료가 발견되면 좋겠네요..

2023-04-14 15:53 UTC, kth990303 commented on src/test/java/mocacong/server/security/auth/apple/AppleOAuthUserProviderTest.java
> +class AppleOAuthUserProviderTest {
올바르지 않은 공개키로 조회 시 claims 획득 시에 예외를 반환하는 상황은 AppleJwtParser의 책임이라 생각이 들어요. AppleJwtParser의 책임을 AppleJwtParserTest에서 테스트 해주고 있습니다. 
개인적으로는 하위 객체의 책임을 상위 객체로 끄집어낼 경우 오히려 객체지향에 위배된다고 생각이 들어요.

다만, claims validate가 올바르지 않을 경우 InvalidTokenException을 반환하는 예외 테스트는 존재하지 않아서 추가로 작성했습니다.

2023-04-14 16:02 UTC, kth990303 commented on src/test/java/mocacong/server/security/auth/apple/ApplePublicKeysTest.java
> +class ApplePublicKeysTest {
> ApplePublicKey 객체에서 kty, kid, alg, n, e 등의 속성이 제대로 저장되어 있는지 확인하는 테스트

해당 테스트는 AppleClientTest에 존재합니다. 이 값들은 apple id server에서 제공해주는 공개키 구성요소 정보들입니다. 만약 null check뿐만 아니라 형식 검증 관련 리뷰라면 해당 테스트는 조금 어렵고 개인적으로 불필요하다고 생각이 들어요. 이 값이 올바른 형식인지에 대해선 애플 측만 알 수 있으며, 검증의 역할도 애플에서 해야된다고 생각해요. 우리는 애플에서 주는 공개키 구성 요소 정보들을 만드는 역할이므로 공개키 구성 요소들로 publicKey (!= ApplePublicKey)를 잘 생성하면 된다고 생각합니다 :)

> keys 리스트 값을 변경 시도해서 불변성 한번 더 체크하는 테스트 

마찬가지로 GET api를 통해 얻어온 List<ApplePublicKey>에 대한 테스트이기 때문에 jackson library에 대해 테스트를 하자는 것과 동일한 코멘트라 생각돼요. jackson library 테스트 코드는 (학습테스트가 아니기 때문에) jackson 측에서 하면 된다고 생각합니다. 만약 우리 측에서 실수나 악의로 public key 정보들을 바꾼다면? 애플에서 준 키 구성 정보들을 바꾸면 AppleJwtParserTest의 아래 테스트에서 걸리게 됩니다.
```java
@Test
@DisplayName("올바르지 않은 public Key로 Claims 획득 시에 예외를 반환한다")
void parseInvalidPublicKeyAndGetClaims() ...
```

따라서 제 개인적인 생각으로는 해당 테스트는 없어도 될 거 같다고 생각이 들어요. 추가로 코멘트나 의문 편하게 남겨주세요 :)

2023-04-14 16:08 UTC, kth990303 commented
우선은 캐싱에 대한 부분을 제외하곤 제 생각을 코멘트로 남겨봤습니다. 일부 테스트도 추가된 부분이 있어서, 테스트 코드에 한해서 리뷰 요청 드립니다 :)

2023-04-14 16:35 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/apple/PublicKeyGenerator.java
> +    public PublicKey generatePublicKey(Map<String, String> headers, ApplePublicKeys applePublicKeys) {
자료는 못찾았지만, https://appleid.apple.com/auth/keys 클릭해서 계속 쳐다보니까 순서쌍 위치만 바뀌고 정보는 그대로네요 ㅎㅎ 캐싱 가능할 것 같습니다.

2023-04-15 04:16 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/auth/apple/PublicKeyGenerator.java
> +    public PublicKey generatePublicKey(Map<String, String> headers, ApplePublicKeys applePublicKeys) {
저도 공개키 업데이트 주기에 관한 자료를 계속 찾아봤는데 공식 문서에도 언급되어 있지 않고 블로그 글도 없네요.. 캐싱방법에 대해서는 한번 gpt한테 물어봤는데 
1. `ConcurrentHashMap` 을 이용한 local cache는 메모리 기반으로 작동하기 때문에 캐시 메모리 용량을 초과하면 성능 저하나 장애가 발생할 수 있다네요.
2. DB를 사용하는 것은 캐시 접근 속도가 메모리 캐시에 비해 느릴 수 있다하네요.
3. AWS Elasticache를 이용한 Redis에 저장하는 방법은 분산 캐시 솔루션으로서 고가용성과 확장성이 우수해서 이 방법을 추천하는 거 같은데

결론적으로 크기가 작은 애플리케이션에서는 `ConcurrentHashMap` 을 이용한 local cache면 충분하지만 크기가 커지면 AWS Elasticache를 적용하는 게 좋다네요. 모카콩에서는 `ConcurrentHashMap` 을 사용해도 충분할 거 같은데 공개키 크기 자체가 작아서 Elasticache를 사용해도 프리티어 용량을 넘지는 않을 거 같아서 둘 중 하나 선택해도 좋을 거 같아요!

2023-04-15 04:19 UTC, Ji-soo708 commented on src/test/java/mocacong/server/security/auth/apple/ApplePublicKeysTest.java
> +class ApplePublicKeysTest {
그렇다면 불필요하다고 생각하네요! 사실 저도 누가 악의적으로 조작한 공개키를 가지고 시도한다면 이미 작성된 테스트의 예외에서 다 걸리지 않을까 생각했어서 코멘트 남길까 말까 고민했는데 이미 있다면 이 정도로 충분한 거 같습니다!

2023-04-15 04:26 UTC, Ji-soo708 approved these changes
시험 기간에도 수고 많으셨습니다! 👏 캐싱에 관해서는 회의할 때 얘기를 더 해봐야겠네요

2023-04-15 04:26 UTC, Ji-soo708 commented on src/test/java/mocacong/server/security/auth/apple/AppleOAuthUserProviderTest.java
> +        when(appleClaimsValidator.isValid(any())).thenReturn(false);
여기서 `false` 리턴하게 해서 클레임 정보가 유효하지 않도록 만들고 예외 잘 던지는지 체크하는 테스트 코드 확인했습니다!

2023-04-15 04:30 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/apple/PublicKeyGenerator.java
> +    public PublicKey generatePublicKey(Map<String, String> headers, ApplePublicKeys applePublicKeys) {
사실상 지금처럼 서버가 한 대일 때에는 1번 방법이 가장 좋습니다만... 개인적으로는 3번이 제일 끌리네요 ㅎㅎ 제일 재밌을 거 같아요

2023-04-15 04:31 UTC, kth990303 commented
캐싱 적용은 해당 PR의 양이 많아질 수 있으니 별도의 브랜치에서 진행하겠습니다.
nonce 값이 최종 확정되면 머지하겠습니다.

2023-04-15 07:56 UTC, kth990303 commented on src/main/java/mocacong/server/security/EncryptUtils.java
> +            return hexString.toString();
Utils 메서드라 생각하여 static 메서드로 만들었습니다. 나중에 spring security 의존성 제거하고 비밀번호 암호화 시에도 해당 메서드가 사용되기 좋겠네요 😄

2023-04-15 07:57 UTC, kth990303 commented on src/main/java/mocacong/server/security/EncryptUtils.java
> +        }
암호화 로직에서 발생한 에러는 서버 쪽 에러라 판단하여 `IllegalArgumentException`을 던지도록 했습니다.

2023-04-15 08:59 UTC, Ji-soo708 approved these changes
메서드 명 관련해서 코멘트 달긴 했으나 케이님 원하시는 대로 하셔도 돼서 바로 approve할게요~ 수고하셨습니다!

2023-04-15 08:59 UTC, Ji-soo708 commented on src/main/java/mocacong/server/security/EncryptUtils.java
> +    public static String encrypt(String value) {
메서드 명에 기능이 더 잘 드러났으면 해서 `encrypt` 보다 `hash` 나 `digest` 가 어떨까요?

2023-04-16 01:08 UTC, kth990303 commented on src/main/java/mocacong/server/security/EncryptUtils.java
> +    public static String encrypt(String value) {
encrypt, hash 둘 중 고민이 됐습니다.
EncryptUtils 클래스에서 암호화 관련 메서드를 찾을 때, `encrypt`, `hash` 중에 전자가 더 찾기 쉬울 거 같아서 유지하는 방향을 선택했습니다.

2023-04-16 01:09 UTC, kth990303 commented on src/main/java/mocacong/server/security/EncryptUtils.java
> +    public static String encrypt(String value) {
우선 이렇게 놔두고, 이후에 스프링 시큐리티 의존성 제거 시에 이름 변경하는 쪽이 낫다면 변경해도 괜찮을 거 같습니다!

2023-04-16 01:09 UTC, merged