feat: 이메일 인증 코드 전송 api 구현
mocacong/Mocacong-Backend pull request #39
Opened 2023-04-20 09:11 UTC by kth990303

## 개요
- 이메일 인증이 요구될 때, 인증코드를 이메일로 전송하는 api를 구현했습니다.

## 작업사항
- aws SES를 이용하여 이메일 전송을 보낼 수 있도록 구현했습니다.
- 현재 모카콩 이메일 인증 프로세스 로직 상, 인증 코드 전송을 Http Message로 한다는 문제점이 있습니다. 하지만 모카콩이 현재 앱으로만 오픈 예정이므로 Http Message를 유저가 뜯어볼 방도가 없다고 판단하여 Http Message로 인증 코드를 보내주는 방식을 유지했습니다.
- 이메일 전송은 비동기로 진행되도록 구현했습니다.

## 주의사항
- aws ses Sandbox에 등록돼있어서 현재는 자격 증명이 완료된 이메일로만 메일 전송이 가능합니다.
- 보안적으로 문제되는 코드가 있는지 확인해주세요.

2023-04-20 09:12 UTC, kth990303 commented on build.gradle
> +	implementation 'commons-io:commons-io:2.11.0'
mvn repository로 최신 의존성임을 확인했습니다. 각각 스프링 환경에서 이메일 전송할 수 있도록 하는 의존성, aws ses 연동 의존성, html 파일을 편리하게 파싱할 수 있는 의존성입니다.

2023-04-20 09:12 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +        String code = String.format("%04d", randomNumber);
4자리 고정을 위해 설정된 부분입니다.

2023-04-20 09:14 UTC, kth990303 commented on src/main/resources/application.yml
> +        queue-capacity: 20
로컬 환경이라 크게 의미있진 않지만 t3.micro 의 vcpu 수가 2개임을 고려하여 임의로 잡아보았습니다. (prod.yml 또한 현재는동일하게 넣을 예정) 별도 부하테스트나 성능테스트는 아직 진행하지 않았습니다.

배포 후에 변동이 생기면 prod.yml 환경에서는 코드변경없이 편리하게 변동할 수 있도록 환경변수 주입을, 로컬은 그냥 이렇게 박았습니다.

2023-04-23 08:26 UTC, Ji-soo708 requested changes
수고하셨습니다. `FileNotFoundException` 관련해서 리뷰 남겼는데 보시고 문제 없다면 바로 Approve 하겠습니다.

2023-04-23 08:26 UTC, Ji-soo708 commented on src/main/resources/application.yml
> +        queue-capacity: 20
t3.micro 인스턴스의 vCPU가 2개이므로, core-size를 2로 설정하는 것은 적절한 거로 보여요. max-size랑 queue-capacity 설정은 저도 어떻게 잡아야 적절한 지 잘 몰라서 gpt에게 물어보니 성능 테스트를 통해 적절한 값을 설정하는 게 제일 좋다고 답하네요. 일단 이렇게 설정해도 문제 없어보입니다!

2023-04-23 08:26 UTC, Ji-soo708 commented on src/main/java/mocacong/server/support/AwsSESSender.java
> +            File file = new File(VERIFY_EMAIL_FILE_PATH);
`FileNotFoundException` 이 발생할 일이 없을까요? 없다면 이대로 작성해도 좋을 거 같아요!

2023-04-23 08:29 UTC, kth990303 commented on src/main/java/mocacong/server/support/AwsSESSender.java
> +            File file = new File(VERIFY_EMAIL_FILE_PATH);
`IOException`이 `FileNotFoundException`의 상위 클래스여서 파일 디렉토리 에러, 파일 형식 에러 등을 처리해줍니다.

2023-04-23 10:47 UTC, Ji-soo708 approved these changes
코멘트 확인했습니다~ 수고하셨어요

2023-04-24 03:20 UTC, merged