feat: 비밀번호 암호화 로직 구현
mocacong/Mocacong-Backend pull request #4
Opened 2023-03-18 09:47 UTC by Ji-soo708

## 개요
- signUp 메서드 안에서 요청으로 들어온 비밀번호를 암호화 해줍니다.

회원가입 테스트 시
![image](https://user-images.githubusercontent.com/69844138/226097601-d1f7ef6c-8122-4aa8-ae08-7c12d66f8fed.png)

## 작업사항
-  Spring Security에서 제공하는 `BCryptPasswordEncoder`를 사용했습니다.
-  `String encode(CharSequence rawPassword)` 메서드는 SHA-2 이상의 알고리즘, 8바이트로 결합된 해쉬, 그리고 랜덤 하게 생성된 솔트를 지원합니다.

## 주의사항
- 오타가 있는지 확인 부탁드립니다.

2023-03-18 14:34 UTC, kth990303 requested changes
수고하셨어요~ 몇가지 코멘트 남겨봤는데 한번 확인해주세요.
추가로 해당 pr은 암호화 로직 구현 기능 커밋만 있는 것이 아니어서 pr 제목을 다른 걸로 바꾸면 어떨까요?

2023-03-18 14:34 UTC, kth990303 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-security'
우리는 spring security 인증/인가 기능을 사용하지 않고 암호화 기능을 위해서 해당 의존성을 추가했는데요! 아예 bcryptPasswordEncoder 없이 SHA-256 암호화 encoding만 할 수 있게 하는 방법도 존재하긴 해요. 

[Password 값 객체를 만들어 spring security 의존성 없이 암호화한 참고 코드](https://github.com/woowacourse/service-apply/blob/master/src/main/kotlin/apply/domain/user/Password.kt)

지금처럼 암호화를 위한 스프링 시큐리티 방법도 좋긴 한데 혹시나 의존성을 아예 없애고 싶을 경우 참고해주세요!

선택지는 총 3가지인 듯해요.
1. 스프링 시큐리티 암호화 O + 스프링 시큐리티 필터 단에서 jwtTokenProvider 이용
2. 스프링 시큐리티 암호화 O + 인터셉터 단에서 jwtTokenProvider 이용
3. 스프링 시큐리티 암호화 X (의존성 제거) + 인터셉터 단에서 jwtTokenProvider 이용

2023-03-18 20:09 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/SpringSecurity.java
> +}
파일 끝 자동 개행 추가 설정했습니다

2023-03-18 20:09 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/SpringSecurity.java
> +public class SpringSecurity extends WebSecurityConfigurerAdapter{
네 좋습니다. `SecurityConfig` 로 바꾸겠습니다!

2023-03-18 20:10 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/SpringSecurity.java
> +    }
감사합니다. 참고해서 바꿨습니다

2023-03-18 20:10 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/MemberService.java
> +                .getId();
테스트코드 추가하겠습니다!

2023-03-19 12:18 UTC, kth990303 approved these changes
수고하셨습니다~ 리뷰 잘 반영해주셔서 감사해요

2023-03-19 12:19 UTC, merged