feat: 카페 이미지 조회 GET API 구현
mocacong/Mocacong-Backend pull request #55
Opened 2023-05-02 07:02 UTC by Ji-soo708

## 개요
- 카페 이미지 조회 api 구현

## 작업사항
- 카페 이미지 조회 GET api를 구현했습니다.
- 정상적인 테스트를 위해 `cafe_image` 테이블 데이터를 초기화하도록 `DatabaseCleaner` 에서 격리 작업을 추가했습니다.
- 카페 이미지 조회 테스트 코드를 작성했습니다.

## 주의사항
- 누락된 테스트 코드가 있는지 확인해주세요.
- 스웨거로 실제 동작 테스트를 확인해주세요.
- 잘못된 로직이 있는지 확인해주세요.
- 리팩터링 해야 할 부분이 있다면 리뷰 부탁드립니다.

2023-05-02 11:10 UTC, kth990303 requested changes
수고하셨어요 일부 코멘트 남겼으니 확인 부탁드려요.

추가로, 카페 이미지 조회가 아닌 카페 조회 화면에서도 imgUrl을 추가로 담아줘야될 거 같아요.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/57135043/235650591-54a4e41c-798c-4ff1-80ca-5ba89370d66a.png">

2023-05-02 11:10 UTC, kth990303 commented on src/main/java/mocacong/server/dto/response/CafeImageResponse.java
> +    private List<CafeImage> cafeImages;
엔티티를 반환해주고 있네요 🤔

2023-05-02 11:10 UTC, kth990303 commented on src/main/java/mocacong/server/dto/response/CafeImageResponse.java
> +    private List<CafeImage> cafeImages;
API docs에서 memberId를 반환하게 해주는 이유는, 자기 자신이 추가한 이미지인지 파악하기 위함인 것 같은데 `isMe:boolean` 값을 보내주는 건 어떨까요?

2023-05-02 11:10 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        return new CafeImageResponse(page, cafeImageList);
페이징 처리는 비즈니스 로직이라 보긴 어려울 듯한데, Spring data jpa의 Paging 기법을 이용해보는 건 어떨까요? #47 을 참고해보면 좋을 거 같아요

2023-05-02 11:10 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
`CAFE_SHOW_PAGE_IMAGES_LIMIT_COUNTS`가 필요 없어보여요.

여기서 `CAFE_SHOW_PAGE_COMMENTS_LIMIT_COUNTS`의 의미는 카페 코멘트 모달뷰를 클릭했을 때의 개수 제한이 아니고, 카페 조회화면 처음 클릭했을 때 보여지는 코멘트 개수입니다.

2023-05-02 11:10 UTC, kth990303 commented on src/test/java/mocacong/server/support/DatabaseCleaner.java
> +    private static final String TRUNCATE_CAFE_IMAGE_TABLE = "TRUNCATE TABLE cafe_image";
직접적으로 지정하면 `@CollectionTable`이 추가될때마다 쿼리문을 추가해야되는 번거로움이 존재할 거 같아요. `@CollectionTable` 어노테이션을 리플렉션을 이용해 로드하는 코드를 작성하여 자동으로 삭제되게 하면 어떨까요?

2023-05-03 10:00 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        return new CafeImageResponse(page, cafeImageList);
처음에 https://github.com/mocacong/Mocacong-Backend/pull/47 을 참고하고 했는데 `Cafe` 엔티티와 `CafeImage` 변환 문제로 중간에 컨버터 클래스를 둬야 Spring data jpa의 Paging 기법이 가능할 거 같아 일단 이렇게 직접 페이징 작업을 했습니다. 아니면 `CafeImage` 레포지토리를 만들어야 하는데 이러면 `CafeImage` 를 엔티티로 만들어야 해서 케이님이 보셨을 때 컨버터 클래스를 둬서 하는 게 나을까요?

2023-05-06 10:36 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +    private static final int CAFE_SHOW_PAGE_IMAGE_LIMIT_COUNTS = 5;
카페 조회 시, 처음에 보이는 카페 이미지 제한 수입니다.

2023-05-06 10:36 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +    private List<CafeImageResponse> findCafeImageResponses(Cafe cafe, Member member) {
카페 조회 시, 카페 이미지를 5개까지 보여주는 메서드입니다.

2023-05-06 10:36 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Cafe.java
>      }
`CafeImageRepository` 생성하면서 카페 이미지 등록 관련 코드를 수정했습니다.

2023-05-07 06:37 UTC, kth990303 requested changes
수고하셨어요 몇가지 코멘트 남겨봤습니다~
그리고 git conflict 해결도 같이 해주시면 좋을 거 같아요

2023-05-07 06:37 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +                    return new CafeImageResponse(cafeImage.getImgUrl(), isMe);
`cafeImage.getMember().equals(member);` 이 부분을 `CafeImage`한테 책임을 위임해보는건 어떨까요? CafeImage에게 메시지를 보내고, CafeImage 도메인이 책임을 가지게 할 수 있어보여요

2023-05-07 06:37 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +    private List<CafeImageResponse> findCafeImageResponses(Cafe cafe, Member member) {
해당 메서드는 `findCafeByMapId` 메서드에 쓰이는 private method니까 메서드 위치 순서를 위쪽으로 옮기는게 좋아보여요

2023-05-07 06:37 UTC, kth990303 commented on src/main/java/mocacong/server/controller/CafeController.java
> +    @GetMapping(value = "/{mapId}/img", produces = MediaType.APPLICATION_JSON_VALUE)
```suggestion
    @GetMapping("/{mapId}/img")
```
이렇게만 있어도 괜찮아보이네요

2023-05-07 06:37 UTC, kth990303 commented on src/main/java/mocacong/server/domain/CafeImage.java
> +    private Cafe cafe;
카페 이미지 입장에서 카페 fetch type은 `LAZY`로 하는게 좋아보이는데 어떤가요?
카페 이미지를 조회할 때, 카페의 모든 정보를 가져오기엔 너무 많기도 하고, 그럴 필요가 없어보인다고 생각해요

2023-05-07 06:37 UTC, kth990303 commented on src/main/java/mocacong/server/domain/CafeImage.java
> +public class CafeImage extends BaseTime {
<img width="539" alt="image" src="https://user-images.githubusercontent.com/57135043/236661076-f31b46fe-e7c3-4daa-a4ee-1d57d593b7e2.png">

아직 조회 작업이어서 없어도 될 것 같긴 하지만 까먹지 않기 위해 남겨둡니다!

2023-05-07 06:37 UTC, kth990303 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +    private CafeImageRepository cafeImageRepository;
안쓰는 `@Autowired` 삭제해도 괜찮아보여요. 추가로 `@Autowired reviewRepository`도 같이 삭제해주시면 감사하겠습니다

2023-05-07 06:37 UTC, kth990303 commented on src/main/java/mocacong/server/controller/CafeController.java
> +    }
새로운 api가 생성됐으니 인수테스트도 진행해보면 어떨까요? 로직 자체는 서비스 레이어 통합테스트로 검증이 됐으니 200 OK 응답이 반환되는지 정도 추가하면 될 거 같아요

2023-05-07 08:05 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +                    return new CafeImageResponse(cafeImage.getImgUrl(), isMe);
넵 생각해보니 서비스에서 처리하는 것보다 도메인에서 책임을 가지는 게 좋을 거 같아 수정하겠습니다.

2023-05-07 08:21 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/CafeImage.java
> +public class CafeImage extends BaseTime {
수정할 때 추가해서 반영하겠습니다👍

2023-05-07 08:47 UTC, kth990303 approved these changes
수고하셨어요 메서드 위치 관련 코멘트 하나 남겼어요.
확인해보시고 머지해주시면 될 거 같습니다~

2023-05-07 08:47 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +    }
이 메서드는 `findCafeByMapId` 메서드에서 쓰이니까 `findCommentResponses` 메서드 밑에 있는게 좋아보여요. 

타 개발자가 모카콩에 들어왔을 때, findCafeByMapId 메서드를 분석할 때, `findCafeImageResponses` 메서드 로직을 보려고 하면 57번째 줄과 232번째 줄을 왔다갔다 함으로써 가독성이 떨어질 수 있을 듯하네요.

2023-05-07 10:51 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +    }
아하 확실히 관련 메서드 바로 아래에 위치시키는 게 좋을 거 같네요. 수정하겠습니다~

2023-05-07 11:00 UTC, merged