feat: 프로필 회원정보 수정 PUT api 구현
mocacong/Mocacong-Backend pull request #60
Opened 2023-05-06 13:54 UTC by Ji-soo708

## 개요
- 프로필 회원정보(닉네임, 비밀번호, 전화번호) 수정 PUT api를 구현했습니다.

## 작업사항
- 프로필 회원정보 수정 PUT API 구현
- 프로필 회원정보 수정 테스트 코드 작성
- 프로필 이미지 수정 컨트롤러 메서드 반환 값 Void로 수정

## 주의사항
- api 명세서와 동일한지 확인해주세요
- 누락된 테스트 코드가 있는지 확인해주세요
- 올바른 로직으로 구현되었는지 확인해주세요

2023-05-06 13:59 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Member.java
> +        if (StringUtils.isBlank(nickname) || StringUtils.isBlank(password) || StringUtils.isBlank(phone)) {
공백 체크를 위해 해당 코드를 추가했습니다. 다른 좋은 방법이 있다면 알려주세요.

2023-05-06 13:59 UTC, Ji-soo708 commented on src/main/java/mocacong/server/dto/request/MemberProfileUpdateRequest.java
> +    @NotBlank(message = "1012:공백일 수 없습니다.")
여기서 `@NotBlank` 를 해도 `validateUpdateInfo()` 에서 `if (StringUtils.isBlank(nickname) || StringUtils.isBlank(password) || StringUtils.isBlank(phone))` 조건문이 없다면 공백 체크가 안되네요. 그래서 `validateUpdateInfo()` 에서 공백 체크를 해주도록 코드 추가했습니다.

2023-05-06 13:59 UTC, Ji-soo708 commented on src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
> +        );
전화번호를 확인할 수 있는 마땅한 방법이 떠오르지 않아 닉네임과 비밀번호만 변경사항이 잘 적용되었는지 확인했습니다. 변경된 전화번호도 검증 코드가 필요하다면 수정하겠습니다.

2023-05-07 07:47 UTC, kth990303 requested changes
왜 dto에서 `@NotBlank`가 적용안됐을지 띠용하셨을 거 같네요ㅋㅋ 관련 코멘트와 추가로 몇몇 리뷰 남겼습니다. 수고하셨습니다.

2023-05-07 07:47 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Member.java
> +        if (StringUtils.isBlank(nickname) || StringUtils.isBlank(password) || StringUtils.isBlank(phone)) {
공백 체크는 request dto에서 하고 있기 때문에 안해도 괜찮아보입니다

2023-05-07 07:47 UTC, kth990303 commented on src/main/java/mocacong/server/exception/badrequest/InvalidArgumentException.java
> +}
없어도 될 거 같은 클래스네요

2023-05-07 07:47 UTC, kth990303 commented on src/main/java/mocacong/server/controller/MemberController.java
> +            @RequestBody MemberProfileUpdateRequest request
```suggestion
            @RequestBody @Valid MemberProfileUpdateRequest request
```

2023-05-07 07:47 UTC, kth990303 commented on src/main/java/mocacong/server/dto/request/MemberProfileUpdateRequest.java
> +    @NotBlank(message = "1012:공백일 수 없습니다.")
request body에 `@Valid`가 빠져서 그렇습니다.

2023-05-07 07:47 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +    }
닉네임 중복체크도 추가해야될 것 같아요. 서비스 레이어에 있는 `validateDuplicateMember`를 이용하면 괜찮아보이네요

2023-05-07 07:47 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +        member.validateUpdateInfo(nickname, password, phone);
서비스에서 validate할 필요 없이 Member 도메인에서 update시에 validate하게 하면 어떨까요?
단, 비밀번호는 서비스에서 인코딩 작업이 들어가니까 비밀번호는 여기서 validate해야겠네요. 49번째 줄에 있는 `validatePassword`를 이용하면 괜찮겠네요

2023-05-07 07:47 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Member.java
> +    }
멤버 입장에서 인코딩 전 비밀번호를 알 필요가 없을 거 같아요

2023-05-07 07:47 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Member.java
> +    }
```suggestion
    public void updateProfileInfo(String nickname, String password, String phone) {
        validateMemberInfo(nickname, phone);
        this.nickname = nickname;
        this.password = password;
        this.phone = phone;
    }
```
여기서만 검증하고, 추가된 다른 도메인 로직은 지워도 괜찮아보이네요.
추가로, public method가 private method보다 위쪽에 있는 게 가독성이 좋을 거 같아요

2023-05-07 07:47 UTC, kth990303 commented on src/test/java/mocacong/server/service/MemberServiceTest.java
> +        assertThat(updatedMember.getPhone()).isEqualTo(newPhone);
assertAll 로 하면 어떨까요?

2023-05-07 07:47 UTC, kth990303 commented on src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
> +        );
서비스 테스트에서 비즈니스 로직이 올바른지 검증 자체는 됐으니, 이 정도면 충분할 듯합니다.

2023-05-07 08:40 UTC, Ji-soo708 commented on src/main/java/mocacong/server/dto/request/MemberProfileUpdateRequest.java
> +    @NotBlank(message = "1012:공백일 수 없습니다.")
그렇네요. 감사합니다.. 좀 더 꼼꼼히 체크해야겠어요🫠

2023-05-07 08:50 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/MemberService.java
> +        member.validateUpdateInfo(nickname, password, phone);
`단, 비밀번호는 서비스에서 인코딩 작업이 들어가니까` 이 문제때문에 일부러 모든 필드를 서비스에서 validate 했던 거였는데 차라리 비밀번호만 서비스에서 validate 하고 나머지 필드는 도메인에서 validate 시켜도 좋을 거 같네요. 👍

2023-05-07 08:52 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/Member.java
> +    }
넵 이 부분 유의하겠습니다.

2023-05-07 09:58 UTC, kth990303 approved these changes
동작 자체는 문제 없어보여서 approve로 합니다만, 몇 가지 반영됐으면 좋겠는 코멘트 남기고 갑니다.
수고하셨어요~ 이것도 머지는 맡기겠습니다.

2023-05-07 09:58 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Member.java
> +    private static final Pattern PASSWORD_REGEX = Pattern.compile("^(?=.*[a-z])(?=.*\\d)[a-z\\d]{8,20}$");
없어도 될 거 같아요

2023-05-07 09:58 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Member.java
> +    }
이 메서드도 필요 없어보여요. `validateMemberInfo`랑 완전히 똑같은 메서드입니다

2023-05-07 10:47 UTC, merged