feat: 비밀번호 확인 인증 POST API
mocacong/Mocacong-Backend pull request #72
Opened 2023-05-12 06:29 UTC by Ji-soo708

## 개요
- 회원정보를 수정하기 전 비밀번호 확인 인증을 하는 API를 구현했습니다.

## 작업사항
- 비밀번호 확인 인증 API 구현
- 비밀번호 확인 인증 테스트 코드 작성

## 주의사항
- api 스펙과 동일하게 구현되었는지 확인해주세요
- 스웨거로 동작 확인해주세요
- 오타가 있는지 확인해주세요

2023-05-12 06:33 UTC, Ji-soo708 commented on src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
> +    @Test
비밀번호 확인 인증에서는 단위 테스트/인수 테스트 모두 옳은 비밀번호 혹은 틀린 비밀번호로 인증할 경우에 대해 테스트 코드를 작성했습니다.

2023-05-12 12:52 UTC, kth990303 requested changes
기능 자체는 문제가 없지만, 로그에 민감정보가 그대로 남을 수 있어보여서 RC로 했습니다~

2023-05-12 12:52 UTC, kth990303 commented on src/main/java/mocacong/server/controller/MemberController.java
> +        PasswordVerifyResponse response = memberService.verifyPassword(email, request.getPassword());
민감정보 로그 마스킹 전략 상 해당 로직을 아래처럼 수정해야될 거 같아요
```suggestion
        PasswordVerifyResponse response = memberService.verifyPassword(email, request);
```

request를 넘기는 경우
`password=abcabc` 형태로 넘어오고 Logger가 password 뒤 부분을 마스킹해줌.

request.getPassword()를 넘기는 경우
`abcabc` 형태로 넘어오고 Logger는 비밀번호인지 알 턱이 없기 때문에 마스킹을 안해줌.

2023-05-13 05:45 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/MemberController.java
> +        PasswordVerifyResponse response = memberService.verifyPassword(email, request.getPassword());
그 부분을 놓쳤네요. 수정하겠습니다 👍

2023-05-13 06:07 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/MemberController.java
> +            @RequestBody @Valid PasswordVerifyRequest request
`request` 전체를 넘겨주도록 변경했습니다.

2023-05-13 06:11 UTC, kth990303 approved these changes
수정사항 확인했습니다 머지해주시면 될거같네요~

2023-05-13 06:18 UTC, merged