feat: 로그인 및 토큰 발급 POST api 구현
mocacong/Mocacong-Backend pull request #8
Opened 2023-03-24 14:28 UTC by Ji-soo708

## 개요
- JWT 토큰 기반 인터셉터 로그인 구현 및 올바른 로그인 요청에 대해 토큰 발급 테스트 코드 작성했습니다.

## 작업사항
- JWT 토큰 기반 인터셉터 로그인 구현했습니다.
- 올바른 로그인 요청에 대해 토큰 발급 테스트 코드를 작성했습니다.

## 주의사항
- 올바른 테스트 코드인지 확인해주세요.
- 누락된 테스트 코드가 있는지 확인해주세요.
- 오타가 있는지 확인해주세요.

2023-03-24 16:54 UTC, kth990303 requested changes
수고 많으셨습니다~ 몇 가지 누락된 테스트 코드, 특정 로직에 대한 궁금증 때문에 리뷰를 정말 많이 남겨드렸어요!
초기 구축 단계인만큼 탄탄하게 설계해야된다고 생각해서 리뷰가 되게 많은데, 시간되실 때 차근차근히 고민해보시고 같이 얘기 나누면 좋을 듯합니다!

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +import mocacong.server.infrastructure.auth.JwtUtils;
안쓰는 import문 제거해주시면 좋을 듯합니다!

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/JwtUtils.java
> +public class JwtUtils {
jwt 관련된 utils 클래스 느낌이라기보단 더 중요한 역할을 하고 있다고 생각이 들어서 네이밍을 `JwtTokenProvider`와 같이 하는 건 어떨까요?

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/JwtUtils.java
> +        Claims claims = Jwts.claims(payload);
여기도 마찬가지로 payload가 `Map<String, Object>`일 필요 없이 String 타입이면 될 거 같은데 어떻게 생각하시나요? claims를 받을 필요 없이 바로 setSubject(payload)로 builder를 사용할 수 있어보여요!

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/JwtUtils.java
> +    }
payload를 제대로 가져오는지 해당 테스트 코드가 있으면 좋을 듯해요

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/JwtUtils.java
> +    }
claims를 사용하지 않게 바뀐다면 해당 로직도 제거할 수 있어보여서 남겨봅니다 :)

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +        }
preflight 처리 놓치지 않고 잘해주셨네요 👍

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +import lombok.NoArgsConstructor;
마찬가지로 안쓰는 import문이 클래스마다 조금씩 있는데 한번 싹 정리해주시면 좋을 듯합니다!

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +        }
`catch`에 해당되는 로직은 우선 지워주셔도 될 거 같아요! 에러처리 관련 pr을 제가 별도로 만들어서 올릴 예정입니다.

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws IOException {
라인이 120자가 넘어가는 것 같은데, 적절한 구간에서 개행해보는 건 어떤가요?
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/57135043/227582575-fe465db0-19ff-4642-8d69-fdd9328636ba.png">

의무적인 사항은 아니지만 보통 최대 줄 사용 너비는 120자 정도를 준수하는 컨벤션이 많이 사용되고 있어서 남겨봅니다~

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/domain/LoginEmail.java
> +}
단순 controller에서 사용되기 위한 어노테이션 클래스이므로 도메인 패키지에 위치하진 않아야될 것 같아요. controller 패키지는 어떻게 생각하시나요?

(이 어노테이션이 붙은 api에서는 `AuthenticationPrincipalArgumentResolver`에 있는 `resolveArgument` 메서드를 자동으로 수행해줍니다. 즉, 도메인 계층 영역이 아닌 컨트롤러 영역에서 처리되는 어노테이션입니다.)

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/config/AuthConfig.java
> +    }
LogTraceIdInterceptor가 아니라 LoginInterceptor가 등록돼야 요청이 들어올 때 preHandle 메서드의 jwt 검증 로직이 수행이 제대로 될 것 같아요

(스프링 내에서 컨트롤러 요청 처리 전에 인터셉터 작업이 처리가 됩니다.)

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/config/AuthConfig.java
> +    }
회원가입 api는 jwt가 없는 상태에서 사용가능해야 할 api이므로 `excludePathPatterns` 해주어야될 듯합니다

2023-03-24 16:54 UTC, kth990303 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    private PasswordEncoder passwordEncoder;
`@MockBean`을 사용하신 이유가 궁금합니다!
mocking을 하지 않고 memberRepository에 회원 정보를 insert한 후, authService에서 해당 회원 정보에 대한 request를 보낼 때 토큰이 발급되는지 확인해주는 로직을 작성해볼 수도 있어보여서 한번 남겨봐요.

사실 mockbean도 나쁘지 않은 방법이라 생각되지만, **개인적으로** mocking은 두 가지 단점때문에 꺼려지는 부분이 있는데요.
1. 실제 repository에 저장됐는지 여부를 무시하고 when (또는 then)으로 결과를 반환한다. -> 이 부분은 사람마다 의견이 다릅니다. (`classicist vs mockist`에 대해 검색해보셔도 좋을 거 같아요~) 저는 실제로 해당 객체가 잘 저장됐는지, 그리고 해당 실제 객체에 대해 비즈니스 로직이 실제 의도대로 잘 반환되는지를 중시하는 편이긴 해서 mocking을 꼭 필요한 상황이 아니면 선호하진 않습니다.
2. `@MockBean`은 너무 느려서 싫어합니다.

한번 확인해주시고 mock에 대한 생각을 자유롭게 적어주시면 좋을 거 같아요!

2023-03-24 16:54 UTC, kth990303 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    @Test
성공하는 케이스 외에, 요청이 올바르지 않은 경우에 예외가 제대로 반환되는지 테스트가 있음 좋을 듯해요!

그 외에 인수테스트로 Http Status Code나 실제 로그인이 End to End로 잘 처리되는지 작성해주면 더 좋을 것 같습니다. 인수테스트가 부담된다면 해당 부분은 제가 담당할게요

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/AuthorizationExtractor.java
> +    public static final String AUTHENTICATION_TYPE = "Bearer";
`private`으로 바꿔도 될 듯합니다!

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/exception/unauthorized/AuthorizationHeaderUninvolvedException.java
> +}
Authorization 헤더에 Bearer 키워드가 없을 때 발생하는 에러네요.
에러명이 조금 길어서 보기 힘든데, InvalidBearerException이나 LoginFailException은 어떤가요? 지금도 나쁘진 않다고 생각합니다.

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/AuthenticationPrincipalArgumentResolver.java
> +        }
사실 저는 해당 로직에서 실패하면 NO_LOGIN이 아니라 에러를 띄워주는 것이 맞다고 생각해요 (jwt가 필요한 api인데 인증없이 접근했다? 401 에러를 보내주는 것이 맞지 않을까)

그리고 그에 관한 에러는 이미 37번째 라인에 해당되는 `extractAccessToken` 메서드에서 해주고 있다고 생각해요. 해당 메서드를 잘 보시면 Authorization 헤더가 `bearer`로 시작하지 않으면 `throw new AuthorizationHeaderUninvolvedException();`를 해주고 있구요! 그래서 사실상 `extractAccessToken`메서드만 있어도 충분하고 hasAccessToken() 메서드나 isOptional() 메서드는 아예 지워도 괜찮다고 생각이 들어요.

(참고로 `hasAccessToken()` 메서드랑 `extractAccessToken()` 메서드는 boolean 반환 타입 외엔 사실상 거의 같습니다.)

어떻게 생각하시는지 코멘트 편하게 남겨주시면 같이 얘기해보면서 정하면 좋을 듯합니다!

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/AuthenticationPrincipalArgumentResolver.java
> +        return LoginUserEmail.from(email);
DTO로 감싸서 반환하기 vs email 값을 보내주기
어떤게 더 나으신가요? 

현재 로직을 적어본다면 아래처럼 될 거 같아요.

LoginUserEmail로 controller에 반환 (즉 jwt를 통한 인증 완료) -> 인증이 됐으니 요청이 들어온 api 처리를 위해 서비스에 접근 -> LoginUserEmail에서 다시 email 얻어오고 memberRepository.findByEmail(email)로 회원 객체 얻어옴. -> 해당 회원에 대한 api 비즈니스 로직 처리

결국은 email 값을 LoginUserEmail로 감싸고, 다시 email을 사용하기 위해 꺼내고... 불필요하게 감싸는 작업이 추가된거긴 해요! DTO로 감싸준 이유가 있을까요?

근데 저는 이 부분은 개인적인 선호도가 딱 반반이긴 합니다! 궁금해서 한 번 여쭤보는거라 편하게 답변해주세요!

2023-03-24 16:54 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
현재 해당 클래스들은 infrastructure라는 패키지에 있는데요! 제 생각에 infra 패키지에 들어가면 좋을 클래스들은 스프링 외의 로직 (ex. redis, 외부 api 사용 등)이 사용될 때라 생각이 들어서 패키지가 적절한지 의문이 들었어요. 해당 부분에 대해 어떻게 생각하시나요?

2023-03-25 10:08 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/logaspect/LogTraceIdInterceptor.java
> +    }
저도 `LogTraceIdInterceptor` 에 대해 찾아봤었는데 꼭 필요한 건 아니지만 이걸 사용하면 각 요청마다 고유한 추적 ID를 생성하고 로그 문장에 추가해줘서 나중에 문제 생겼을 때 추적하기 좋다고 해서 추가해놨습니다. AuthConfig쪽에서도 일단 `LogTraceIdInterceptor` 를 등록해서 모든 요청에 대해 해당 인터셉터를 적용해놨습니다!

2023-03-25 10:10 UTC, Ji-soo708 commented on src/main/java/mocacong/server/exception/badrequest/IdPasswordMismatchException.java
> +    }
넵 수정하겠습니다!

2023-03-25 10:10 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/MemberService.java
> +import mocacong.server.infrastructure.auth.JwtUtils;
넵 수정하였습니다!

2023-03-25 10:11 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/JwtUtils.java
> +public class JwtUtils {
네 좋습니다~

2023-03-25 10:13 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +import lombok.NoArgsConstructor;
한번에 수정해서 푸쉬하겠습니다!

2023-03-25 10:16 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws IOException {
알겠습니다! 수정하겠습니다~

2023-03-25 10:19 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/LoginEmail.java
> +}
넵 좋습니다. controller 패키지에 하위 패키지 하나 더 만들어서 넣을까요 아니면 바로 controller 패키지에 위치시키는 게 좋을까요?

2023-03-25 10:22 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/AuthConfig.java
> +    }
아 이렇게 되면 LogTraceIdInterceptor 가 필요 없어지겠네요! 이 부분은 제가 따로 공부하겠습니다 감사합니다.:)
수정했습니다!

2023-03-25 10:25 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/AuthConfig.java
> +    }
그걸 생각 못했네요...🥲 수정하겠습니다!

2023-03-25 10:26 UTC, kth990303 commented on src/main/java/mocacong/server/domain/LoginEmail.java
> +}
controller 하위에 패키지 만들어주셔도 좋고, 아니면 아예 별도로 support 패키지를 생성해도 괜찮을 듯해요! 도메인이나 서비스쪽만 아니면 될 듯합니다

2023-03-25 10:35 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    private PasswordEncoder passwordEncoder;
처음에 `@MockBean` 사용 안하고 테스트코드 작성하다가 에러나서 저도 이번에 이 부분에 대해 공부를 했는데 느리다는 단점은 제가 캐치하지 못했고 단순히 `AuthService` 를 제외한 `MemberRepository`, `JwtUtils`, `PasswordEncoder`, `AuthService` 가 해당 `AuthServiceTest` 클래스와 연결되지 않기에 `@MockBean` 으로 처리를 했습니다.
하지만 `@MockBean`이 너무 느리다는 단점이 있다면 원석님이 제안해주신 로직으로 테스트 코드를 수정하는 게 좋을 거 같습니다! 지적 감사합니다.:)

2023-03-25 10:35 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    @Test
넵 일단 두가지 테스트 코드 작성 시도 해보겠습니다!

2023-03-25 10:39 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/AuthorizationExtractor.java
> +    public static final String AUTHENTICATION_TYPE = "Bearer";
수정했습니다!

2023-03-25 10:41 UTC, Ji-soo708 commented on src/main/java/mocacong/server/exception/unauthorized/AuthorizationHeaderUninvolvedException.java
> +}
막상 짤 때는 신경 안쓰였는데 이렇게 보니 신경쓰이네요... InvalidBearerException 으로 수정하겠습니다!

2023-03-25 10:48 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
infra랑 infrastructure 랑 같은 의미가 아닌가요? infra로 바꿔도 의미는 통할 거 같아 패키지명 수정에는 동의하지만 단순 궁금해서 질문드립니다!

2023-03-25 10:58 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/AuthService.java
> +                .build();
JwtUitls.java 에서 남겨주신 리뷰까지 보니까 email 값을 바로 받아와 jwt를 생성해도 좋을 거 같습니다! 좋은 지적 감사합니다.😊

2023-03-25 10:58 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/JwtUtils.java
> +        Claims claims = Jwts.claims(payload);
넵 위에서 남겨주신 리뷰 참고해서 코드 수정했습니다!

2023-03-25 11:01 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/JwtUtils.java
> +    }
확인했습니다! 정말 케이님이 제시한 대로 하니 코드가 간결해지네요! 감사합니다:)

2023-03-25 11:03 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
둘이 같은 의미가 맞고 infra 말고 다른 패키지명이 좋을 거 같다는 리뷰입니다!

2023-03-25 11:16 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    private PasswordEncoder passwordEncoder;
payload() 관련해서 테스트코드 짜려면 어쩔 수 없이 `@Autowired` 써야 하네요.🤣 케이님이 말씀하신 대로 수정했습니다!

2023-03-25 11:16 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/JwtUtils.java
> +    }
좋습니다! 추가 테스트코드 작성하겠습니다~

2023-03-25 13:40 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/AuthenticationPrincipalArgumentResolver.java
> +        }
넵 좋습니다. 다른 곳에서 같은 부분을 처리해주니까 해당 부분은 지워도 될 거 같습니다! 감사합니다.:)

2023-03-25 14:04 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/AuthenticationPrincipalArgumentResolver.java
> +        return LoginUserEmail.from(email);
email 로 바로 반환하는 것보다 dto로 감싸서 주는 게 보안적으로 조금 더 안전하지 않나요? 보안이랑 상관없다면 수정할 의향이 있습니다!

2023-03-25 14:47 UTC, kth990303 commented on src/main/java/mocacong/server/infrastructure/auth/AuthenticationPrincipalArgumentResolver.java
> +        return LoginUserEmail.from(email);
서버 내에서 처리되면서 사용되는거라 크게 보안적 이슈는 없다고 생각돼요! 

혹시 해당 관련 보안 이슈 자료가 따로 있나요?

2023-03-26 00:12 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
네, 일단 intergration 으로 변경하겠습니다!

2023-03-26 00:15 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/LoginEmail.java
> +}
`LoginEmail` 은 삭제했습니다! 답변 감사합니다~

2023-03-26 00:25 UTC, Ji-soo708 commented on src/main/java/mocacong/server/infrastructure/auth/AuthenticationPrincipalArgumentResolver.java
> +        return LoginUserEmail.from(email);
아하 보안 이슈가 없다면 바로 email로 주는 게 더 간결할 거 같아 그렇게 수정하겠습니다! 
보안을 언급했던 건 그냥 DTO가 캡슐화 역할을 하는 거로 알고 있어서 언급한 건데 생각해보니 LoginEmail에서는 email 값 하나만 주니까 차라리 바로 email로 주는 게 더 효율적일 거 같네요! 지적 감사합니다.

2023-03-26 02:27 UTC, Ji-soo708 commented
리뷰에 남겨주신 수정 요청 사항들 다 반영해서 고쳤습니다~ 꼼꼼한 리뷰 감사합니다! 😀

2023-03-26 02:45 UTC, kth990303 requested changes
수고하셨어요! 조금만 더 화이팅합시다!

2023-03-26 02:45 UTC, kth990303 commented on build.gradle
> +	implementation 'org.apache.commons:commons-lang3:3.12.0'
`org.apache.commons:commons-lang3:3.12.0` 라이브러리는 사용하는 곳이 없어보여요

2023-03-26 02:45 UTC, kth990303 commented on build.gradle
> +	implementation 'javax.validation:validation-api:2.0.1.Final'
`2.0.1.Final` 버전을 명시하지 않아도 괜찮아보여요.

추가로, `spring-boot-starter-validation`와 `javax.validation:validation-api`중 후자를 선택한 이유도 궁금합니다. 궁금해서 저도 찾아봤는데 많은 정보가 나오진 않더라구요 ㅠㅠ 둘 중 아무거나 사용해도 괜찮아보이긴 하는데 호기심에 코멘트 남겨봅니다.

2023-03-26 02:45 UTC, kth990303 commented on src/main/java/mocacong/server/exception/badrequest/IdPasswordMismatchException.java
> +public class IdPasswordMismatchException extends InputFieldException {
비밀번호 쪽만 체크하므로 클래스명도 `PasswordMismatchException`이 더 나아보이는데 어떤가요?

2023-03-26 02:45 UTC, kth990303 commented on src/main/java/mocacong/server/controller/AuthController.java
> +    }
swagger PR이 머지가 됐기 때문에, `MemberController`처럼 swagger 설정을 추가해주면 좋을 듯해요!

2023-03-26 02:45 UTC, kth990303 commented on src/main/java/mocacong/server/dto/request/AuthLoginRequest.java
> +    private String password;
email, password에 `@NotBlank`, `@Email`와 같은 validation 을 추가해보는건 어떤가요?

2023-03-26 02:45 UTC, kth990303 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    }
해당 부분은 AuthService 레이어 테스트라기보단 JwtTokenProvider 테스트에 가까워서 JwtTokenProviderTest 클래스를 새로 만드는 것이 나아보입니다!

2023-03-26 02:45 UTC, kth990303 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +package mocacong.server.itegration.auth;
패키지명 오타일까요?

2023-03-26 02:45 UTC, kth990303 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +    }
```suggestion
        return jwtTokenProvider.getPayload(token);
    }
```

2023-03-26 02:45 UTC, kth990303 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +    }
`LoginEmail`은 불필요한 dto라서 없애는 것에 동의하되, `LoginUserEmail`까지 없애면 안된다고 생각해요. `supportsParameter` 메서드에서 바인딩할 객체를 지정해주어야 컨트롤러에서 해당 어노테이션 (ex. LoginUserEmail)이 붙은 api에서 인증여부를 확인해줄 수 있기 때문이에요. 

 ```suggestion
    @Override
    public boolean supportsParameter(MethodParameter parameter) {
         return parameter.hasParameterAnnotation(LoginUserEmail.class);
    }
```
위와 같은 방법은 어떤가요? 참고로 클래스명은 어떻든 상관없습니다.

2023-03-26 02:45 UTC, kth990303 commented on src/main/java/mocacong/server/itegration/auth/JwtTokenProvider.java
> +public class JwtTokenProvider {
해당 클래스 테스트를 만든 후, 클래스 메서드에 대한 테스트가 있으면 좋을 듯해요!
JwtTokenProviderTest 클래스가 있다면 해당 프로덕션에 대한 검증 뿐만 아니라 해당 객체가 어떠한 역할을 하는지, 만료된 토큰을 올바르게 검증해내는지에 대한 문서화 역할까지 올바르게 될 듯해요~

- 테스트 코드만으로 해당 JwtTokenProvider가 무슨 역할을 하는지 알아보기 쉽다고 생각되는 예제 사진을 첨부합니다.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/57135043/227752339-9f88b3dd-7a98-4dea-ace8-1ffdf7b453f0.png">

2023-03-26 02:50 UTC, Ji-soo708 commented on build.gradle
> +	implementation 'org.apache.commons:commons-lang3:3.12.0'
깜빡하고 삭제를 못했네요. 알려주셔서 감사합니다!

2023-03-26 02:52 UTC, Ji-soo708 commented on build.gradle
> +	implementation 'javax.validation:validation-api:2.0.1.Final'
저도 찾아봤는데 전자의 경우 Spring Boot에서 Java Bean Validation을 사용할 때 편리하게 사용하기 위해, 후자의 경우 Java Bean Validation API를 사용할 때 사용한다네요!
큰 차이는 없어보입니다.

2023-03-26 02:52 UTC, Ji-soo708 commented on src/main/java/mocacong/server/exception/badrequest/IdPasswordMismatchException.java
> +public class IdPasswordMismatchException extends InputFieldException {
수정하겠습니다. 지적 감사합니다! 😊

2023-03-26 02:53 UTC, Ji-soo708 commented on src/main/java/mocacong/server/controller/AuthController.java
> +    }
네, swagger 설정 추가해서 push 하겠습니다!

2023-03-26 03:05 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    }
클래스 새로 파서 옮기겠습니다~

2023-03-26 03:12 UTC, Ji-soo708 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +package mocacong.server.itegration.auth;
생각해보니 패키지명을 잘못 지은 거 같네요. 이렇게 수정해도 될까요?
com.mocacong.server.security
   |- auth
   |    |- AuthenticationPrincipalArgumentResolver.java
   |    |- AuthorizationExtractor.java
   |    |- JwtTokenProvider.java
   |
   |- interceptor
        |- LoginInterceptor.java

2023-03-26 03:19 UTC, Ji-soo708 commented on src/main/java/mocacong/server/dto/request/AuthLoginRequest.java
> +    private String password;
오 감사합니다! 추가했습니다~

2023-03-26 03:20 UTC, Ji-soo708 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +    }
제안 감사합니다~

2023-03-26 03:33 UTC, kth990303 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +package mocacong.server.itegration.auth;
네 제시해준 방향도 괜찮아보이고 아니면 security.auth에 합쳐도 좋아보입니다

2023-03-26 03:38 UTC, Ji-soo708 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +    }
```java
@Override
    public boolean supportsParameter(MethodParameter parameter) {
        return parameter.getParameterType().equals(LoginUserEmail.class);
    }
```
혹시 이런 방식도 괜찮나요? 케이님이 주신 코드를 적용하려면 기존에 있었던 `LoginUserEmail` 을 수정해야 할 거 같은데 제가 제시한 코드는 파라미터의 타입이 `LoginUserEmail` 인지 여부를 확인하는 거라 결국 케이님이 제시하신 거랑 같은 동작을 한다고 생각해서 질문드립니다!

2023-03-26 03:40 UTC, Ji-soo708 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +package mocacong.server.itegration.auth;
넵 인터셉터까지 `auth` 에 합치겠습니다~

2023-03-26 03:42 UTC, Ji-soo708 commented on src/main/java/mocacong/server/itegration/auth/JwtTokenProvider.java
> +public class JwtTokenProvider {
넵 알겠습니다. 참고해서 예외 테스트 코드까지 짜보겠습니다~ 감사합니다:)

2023-03-26 03:50 UTC, kth990303 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +    }
네 동작만 제대로 되면 괜찮을 듯합니다! 큰 문제 없어보일 거 같아요. 지금은 아직 인증 필요한 api도 없어서 정확하게 체크하긴 어려울 듯한데 혹시나 만약 문제생기면 나중에 고치죠~

2023-03-26 04:52 UTC, Ji-soo708 commented on src/main/java/mocacong/server/itegration/auth/AuthenticationPrincipalArgumentResolver.java
> +    }
넵 알겠습니다~

2023-03-26 05:12 UTC, Ji-soo708 commented
다시 확인해주시면 감사합니다! ☺️

2023-03-26 10:05 UTC, kth990303 approved these changes
수고하셨습니다! 제가 별도로 수정한 사항도 있으니 확인해보세요.
리팩터링하실 부분이 있다면 별도로 하셔도 좋습니다.
머지는 메리에게 맡길게요~~

2023-03-26 10:05 UTC, kth990303 commented on src/main/java/mocacong/server/dto/LoginUserEmail.java
> +}
`LoginUserEmail`을 어노테이션으로 바꿨어요.
아래와 같이 쓰일 예정이어서요!

```java
@Operation(summary = "마이페이지 조회")
@PostMapping
public ResponseEntity<MypageResponse> mypage(
    @LoginUserEmail String email, 
    @RequestBody MypageRequest request
) {
        MypageResponse response = memberService.findMyPage(request);
        return ResponseEntity.ok(response);
}
```

2023-03-26 10:05 UTC, kth990303 commented on src/main/java/mocacong/server/config/AuthConfig.java
> +                .excludePathPatterns("/swagger-resources/**", "/swagger-ui/**", "/v3/api-docs", "/error")
swagger 설정도 exclude 해줘야 되더라고요. + LoginInterceptor 에서도!
(만약 우리 api가 `/api/members`와 같이 앞에 부가적인 무언가가 붙는다면 해당 이슈는 없는데, 그렇지 않으니 생기더라구요)

따로 exclude 안하면 아래 화면이 뜹니다.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/57135043/227768552-c2cabff5-bc3e-4ead-b079-5477f886f3f5.png">

2023-03-26 10:05 UTC, kth990303 commented on src/main/java/mocacong/server/security/auth/LoginInterceptor.java
> +    }
마찬가지로 prehandle 에서 스웨거 처리한 부분

2023-03-26 10:05 UTC, kth990303 commented on src/test/java/mocacong/server/security/auth/JwtTokenProviderTest.java
> +        }
꼼꼼하게 잘해주셨네요.
다만 이 테스트는 무조건 1초 이상은 소요될 듯하네요.
지금은 크게 문제 없을 것 같은데, 이후에 테스트 속도가 좀 느리다 싶으면 수정하죠!

2023-03-26 10:09 UTC, Ji-soo708 commented on src/main/java/mocacong/server/config/AuthConfig.java
> +                .excludePathPatterns("/swagger-resources/**", "/swagger-ui/**", "/v3/api-docs", "/error")
오 참고하겠습니다! 감사합니다~

2023-03-26 10:10 UTC, Ji-soo708 commented on src/test/java/mocacong/server/security/auth/JwtTokenProviderTest.java
> +        }
넵 알겠습니다~

2023-03-26 10:10 UTC, merged

2023-03-27 00:25 UTC, kth990303 commented on build.gradle
> +	implementation 'javax.validation:validation-api:2.0.1.Final'
`org.springframework.boot:spring-boot-starter-validation` 이 아닌 `javax.validation:validation-api:2.0.1.Final` 으로 하면 @Valid가 아예 먹히지를 않네요. spring boot 2.2 버전 이후부터 그런 듯합니다.
https://stackoverflow.com/questions/48614773/spring-boot-validation-annotations-valid-and-notblank-not-working