feat: 즐겨찾기한 카페 필터링 조회 POST API 구현
mocacong/Mocacong-Backend pull request #87
Opened 2023-05-24 10:26 UTC by Ji-soo708

## 개요
- 즐겨찾기한 카페를 필터링하여 카페 목록을 조회하는 API를 구현했습니다.

## 작업사항
- 즐겨찾기한 카페 필터링 조회 POST API 구현
- 즐겨찾기한 카페 필터링 조회 테스트코드 작성

## 주의사항
- api spec에 맞게 구현되었는지 확인해주세요
- 오타가 있는지 확인해주세요
- 더 나은 로직이 있다면 알려주세요

2023-05-24 10:27 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +    public CafeFilterFavoritesResponse filterCafesByFavorites(String email, CafeFilterFavoritesRequest request) {
`filterCafesByStudyType` 로직과 동일합니다.

2023-05-24 12:43 UTC, kth990303 requested changes
서비스 로직, 쿼리가 조금 더 개선되면 좋을거같아서 RC로 남겼어요~

2023-05-24 12:43 UTC, kth990303 commented on src/main/java/mocacong/server/repository/CafeRepository.java
> +    List<Cafe> findByFavoriteCafes(String email);
`mapId`만 반환하면 되는데 cafe 전체 컬럼들을 모두 가져오는건 비효율적일 듯 해요.
`mapId`는 이제 인덱스도 적용되니까 커버링 인덱스 효과도 볼겸, mapId만 가져오게 하면 어떨까요

2023-05-24 12:43 UTC, kth990303 commented on src/main/java/mocacong/server/service/CafeService.java
> +        return new CafeFilterFavoritesResponse(filteredIds);
회원의 모든 즐겨찾기 카페 조회 -> mapId 따로 조회 (N+1문제) -> 거기서 request.getMapIds()와 비교하여 따로 필터링하는 작업은 좀 느릴 수 있을듯해요.

만약 repository에서 아래 작업을 해준다면 어떨까요?
```sql
@Query("select c.mapId from Favorite f " +
        "join f.cafe c join f.member m " +
        "where c.mapId in :mapIds and m.email = :email")
List<String> findCafeMapIdsByMyFavoriteCafes(String email, List<String> mapIds);
```
`in`절을 활용하면 한번에 처리가능할 거 같네요

2023-05-24 12:43 UTC, kth990303 commented on src/main/java/mocacong/server/repository/CafeRepository.java
> +    List<Cafe> findByFavoriteCafes(String email);
추가로 `@Query`를 이용하여 spring data jpa 제공 메서드가 아닌 커스텀 쿼리를 만들었으므로 Repository Test가 있어도 좋을거같네요

2023-05-24 13:36 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        return new CafeFilterFavoritesResponse(filteredIds);
오 좋습니다. 사실 저도 이 부분에서 시간 복잡도가 좀 걸릴 거 같아서 고민하다가 올렸는데 케이님이 제시하신 방법으로 바꾸는 게 더 좋을 거 같네요.👍

2023-05-25 04:40 UTC, kth990303 approved these changes
문제 없는 것 같네요.
approve하고 코멘트 확인 후에 머지해주시면 되겠습니다

2023-05-25 04:40 UTC, kth990303 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        favoriteRepository.save(new Favorite(member2, cafe4));
크게 상관은 없지만, 사실상 해당 연산은 필요 없어보여서 없애면 성능이 더 올라갈 거 같아요.
member2 자체를 없애는것도 괜찮을거같아요

2023-05-25 17:01 UTC, merged