fix: save 메소드 동시성 문제 해결
mocacong/Mocacong-Backend pull request #92
Opened 2023-06-01 17:38 UTC by Ji-soo708

## 개요
- 사용자가 빠르게 여러 번 save를 시도하면 동시성 문제가 일어나는 것을 발견했습니다. 동시성 문제는 unique 속성으로 해결했습니다.

## 작업사항
- 회원가입 동시성 문제 해결 및 테스트 코드 추가
- 카페 등록 동시성 문제 해결 및 테스트 코드 추가
- 카페 리뷰 등록 동시성 문제 해결 및 테스트 코드 추가
- 카페 이미지 등록 동시성 문제 해결 및 테스트 코드 수정 및 추가
- 카페 즐겨찾기 등록 동시성 문제 해결 및 테스트 코드 추가

## 주의사항
- 카페 코멘트의 경우 한 사람이 카페에 여러 댓글을 달 수 있고 코멘트의 유일성을 보장해주는 필드가 id 외에는 없습니다. 그래서  unique로는 해결이 불가능하다고 생각해 해당 기능은 제외하고 올렸지만 unique로 해결이 가능하다면 알려주세요.
- 동시성 문제 해결이 필요한 기능이 더 있다면 알려주세요
- 올바르게 예외 핸들링이 되었는지 봐주세요

2023-06-02 06:44 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/MemberService.java
> +        try{
동시성 문제를 방지하기 위해 `save` 관련 함수들은 try-catch 문 추가했습니다.

2023-06-02 06:48 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        String expected1 = "test_img.jpg";
동시성 방지를 위해 중복되는 url 사진을 여러 번 올리려 하면 막아놓도록 했습니다. 
테스트 코드에서도 파일명을 다르게 해야 테스트가 통과돼서 여러개의 사진들을 추가했는데 그래서 카페 이미지 관련 테스트 코드들이 더러워졌네요.. 좋은 방법이 있을까요

2023-06-03 00:13 UTC, kth990303 requested changes
코드 아주 좋습니다 동시성 해결 잘해주신 것 같아요.
카페 이미지 쪽이랑, 깃 충돌, 그리고 테스트 위치 관련해서 코멘트 남겨봤습니다

2023-06-03 00:13 UTC, kth990303 commented on src/main/java/mocacong/server/service/FavoriteService.java
> +        }
자동정렬 기능 한번씩 이용해주세요~

2023-06-03 00:13 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +        try{
네 괜찮아보입니다.

2023-06-03 00:13 UTC, kth990303 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        MockMultipartFile mockMultipartFile6 = new MockMultipartFile("test_img6", expected6, "jpg", fileInputStream6);
실제 에러나는 이유 중에 하나는 `FileInputStream`을 재활용하는 원인도 있을 듯해요. (stream은 한 번 쓰면 닫히고 다시 사용 못함)

어차피 mock multipartfile을 만드는 것이어서 아래와 같이 쓰면 될 것 같아요.

`new MockMultipartFile("test_img6", "test_img6.jpg", "jpg", new FileInputStream("src/test/resources/images/test_img2.jpg"));`와 같이 소스 위치는 `test_img2.jpg`이지만 파일명은 `test_img6`으로 처리되게. 

그러면 `resources/images`에서 `test_img3.jpg`부터 `test_img7.jpg`를 굳이 삽입하지 않아도 괜찮아보여요

```suggestion
        MockMultipartFile mockMultipartFile1 =
                new MockMultipartFile("test_img1", "test_img1.jpg", "jpg", new FileInputStream("src/test/resources/images/test_img.jpg"));
        MockMultipartFile mockMultipartFile2 =
                new MockMultipartFile("test_img2", "test_img2.jpg", "jpg", new FileInputStream("src/test/resources/images/test_img.jpg"));
        MockMultipartFile mockMultipartFile3 =
                new MockMultipartFile("test_img3", "test_img3.jpg", "jpg", new FileInputStream("src/test/resources/images/test_img.jpg"));
        MockMultipartFile mockMultipartFile4 =
                new MockMultipartFile("test_img4", "test_img4.jpg", "jpg", new FileInputStream("src/test/resources/images/test_img2.jpg"));
        MockMultipartFile mockMultipartFile5 =
                new MockMultipartFile("test_img5", "test_img5.jpg", "jpg", new FileInputStream("src/test/resources/images/test_img2.jpg"));
        MockMultipartFile mockMultipartFile6 =
                new MockMultipartFile("test_img6", "test_img6.jpg", "jpg", new FileInputStream("src/test/resources/images/test_img2.jpg"));
```

2023-06-03 00:13 UTC, kth990303 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        when(awsS3Uploader.uploadImage(mockMultipartFile)).thenReturn("test_img.jpg");
실제로는 `test_img.jpg`로 반환안되고 `UUID.random() + fileName` 형태로 저장되고, 서버 입장에선 (한 유저가 한 요청 당 같은 사진을 올리는 경우가 아닌) 동시성 이슈로 여러 번 올려지는 파일이 서로 다른 것인지 알 방도는 없다고 생각이 들어요. 그래서 이 테스트는 삭제하는 게 나아보이는데 어떤가요?

2023-06-03 00:13 UTC, kth990303 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        List<Cafe> actual = cafeRepository.findAll();
동시성 관련 테스트 잘해주셨습니다.
그런데 `CafeServiceTest`가 많이 길어지기도 하고, 일반적인 비즈니스로직 테스트와는 다른 종류의 테스트라는 생각이 들어요. `CafeConcurrentServiceTest.class` 를 만들어서 거기에 동시성 관련 테스트를 넣는 것은 어떤가요?

`MemberConcurrentTest.class`, `FavoriteConcurrentServiceTest.class` 도 마찬가지입니다

2023-06-03 03:18 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/CafeService.java
> +        }
네 좋습니다 👍

2023-06-03 03:24 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/CafeImage.java
> +    @Column(name = "img_url", unique = true)
아하 다른 사용자랑 겹칠 수 있다는 걸 놓쳤네요...
그렇다면 추천하신 방법이 member와 fileName을 복합유니크 거는 거라 하셨는데 member와 imgUrl 거는 거 의미하시는 건가요? 맞다면 간단하니까 지금 바로 수정해서 푸쉬해도 좋을 거 같아요.

2023-06-03 03:29 UTC, kth990303 commented on src/main/java/mocacong/server/domain/CafeImage.java
> +    @Column(name = "img_url", unique = true)
imgUrl != fileName입니다.
imgUrl은 위에서 적은대로 `UUID.random() + fileName`입니다. 따라서 만약 fileName을 추가한다면 컬럼을 새로 추가해주아야 합니다.

다만 member + fileName 복합유니크 제약을 걸면, 한 유저가 같은 파일명의 다른 사진을 여러개 올릴 때 에러를 반환한다는 문제점이 존재하긴 해요. (같은 파일명이지만 다른 사진인 경우가 많을진 모르겠지만)

2023-06-03 03:30 UTC, kth990303 commented on src/main/java/mocacong/server/domain/CafeImage.java
> +    @Column(name = "img_url", unique = true)
imgUrl은 겹칠 일이 사실상 거의 없어요. 동시성 이슈 발생한다해도 uuid가 실행될때마다 imgUrl은 매번 달라져서요

2023-06-03 03:58 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        when(awsS3Uploader.uploadImage(mockMultipartFile)).thenReturn("test_img.jpg");
네 좋습니다. 해당 테스트는 진행할 이유가 없어보이네요

2023-06-03 03:59 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        MockMultipartFile mockMultipartFile6 = new MockMultipartFile("test_img6", expected6, "jpg", fileInputStream6);
FileInputStream을 재활용하면 안된다는 걸 지금 알았네요 🙃 제시한 코드 사용하니까 확실히 코드가 줄어드네요. 감사합니다 👏

2023-06-03 04:18 UTC, Ji-soo708 commented on src/main/java/mocacong/server/domain/CafeImage.java
> +    @Column(name = "img_url", unique = true)
음 그러면 일단 카페 이미지 동시성 관련 코드를 롤백하는 게 좋을 거 같네요. 케이님 코멘트대로 라면 만약 어떤 유저가 이미지를 구분하기 쉬운 파일명(ex. 1, 2, 3)으로 수정 후에 올리면(제가 그럽니다 ㅎㅎ..) 결국 에러가 발생한다는 거니 이 부분은 어떻게 하는 게 좋을지 더 고민하는 게 좋을 거 같아요.

2023-06-03 05:01 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/CafeServiceTest.java
> +        FileInputStream fileInputStream = new FileInputStream("src/test/resources/images/" + expected);
카페 이미지 관련 코드 롤백 & conflicts 문제 때문에 develop 브랜치 테스트 코드로 바꿨습니다.

2023-06-03 11:37 UTC, kth990303 commented on src/main/java/mocacong/server/domain/CafeImage.java
> +    @Column(name = "img_url", unique = true)
프론트 측에서도 일단 동시성 이슈를 막을 방법이 있다고 하니 이부분은 이후에 고민해봐도 괜찮을듯하네요
사실 카페이미지 동시성 막을 필요가 없을거같기도 하다는 생각도 들어서요ㅎㅎ

2023-06-03 11:43 UTC, kth990303 approved these changes
웬만한 이슈는 다 괜찮게 처리될 것 같네요
일부 코멘트 남겼으니 확인해주시고 머지하면 될거같습니다~

2023-06-03 11:43 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Member.java
> +    @Column(name = "email", unique = true, nullable = false)
닉네임도 `unique = true` 옵션 있어야될 거 같긴 하네요

2023-06-03 11:43 UTC, kth990303 commented on src/test/java/mocacong/server/concurrency/CafeConcurrentServiceTest.java
> +package mocacong.server.concurrency;
서비스 테스트에 속하긴 하므로 concurrency 패키지가 아닌 service 패키지에 넣는 건 어떤가요?

2023-06-03 11:43 UTC, kth990303 commented on src/test/java/mocacong/server/concurrency/CafeConcurrentServiceTest.java
> +        );
아래 방법도 괜찮을 거 같기도 하네요
```suggestion
        assertAll(
                () -> assertThat(exceptions).hasSize(2),
                () -> assertThat(actual).hasSize(1)
        );
```

2023-06-03 11:43 UTC, kth990303 commented on src/main/java/mocacong/server/service/FavoriteService.java
> +        Member member = memberRepository.findByEmail(email).orElseThrow(NotFoundMemberException::new);
크게 상관없는 부분이긴 하지만, 보통 한줄에 `.`은 하나만 쓰는 컨벤션이 좋기는 해요.
```suggestion
        Cafe cafe = cafeRepository.findByMapId(mapId)
                .orElseThrow(NotFoundCafeException::new);
        Member member = memberRepository.findByEmail(email)
                .orElseThrow(NotFoundMemberException::new);
```

2023-06-03 12:38 UTC, Ji-soo708 commented on src/test/java/mocacong/server/concurrency/CafeConcurrentServiceTest.java
> +        );
이 방법도 예외가 2번 일어났다는 걸 잘보여주는 거 같아서 좋네요 👍

2023-06-03 12:42 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/FavoriteService.java
> +        Member member = memberRepository.findByEmail(email).orElseThrow(NotFoundMemberException::new);
넵 유의해서 작성할게요!

2023-06-03 13:24 UTC, merged