fix: 이메일과 플랫폼 일치 여부를 확인하는 회원 중복 체크로 변경
mocacong/Mocacong-Backend pull request #99
Opened 2023-06-07 14:59 UTC by Ji-soo708

## 개요
- 기존 회원가입 로직에서는 회원 중복 체크를 할 때 이메일로만 검증했으므로 OAuth 이메일과 동일한 이메일로 회원가입을 진행할 시 `DuplicateMemberException`이 터졌습니다. 이를 방지하기 위해 uniqueConstraints를 적용해 회원가입 시, `email` 과 `platform` 이 함께 일치하는 경우에만 `DuplicateMemberException`를 던지도록 변경했습니다.

## 작업사항
- Member 엔티티에 uniqueConstraints 추가
- 회원 중복 체크 로직 수정
- 회원가입을 진행한 이메일로 OAuth 로그인을 시도할 때 정상적으로 작동하는 지 검증하는 테스트 코드 추가

## 주의사항
- 회원 중복 체크 로직이 올바른지 확인해주세요
- Kakao OAuth 로그인으로 uniqueConstraints가 적용되었음을 확인했습니다
- 추가된 테스트 코드가 올바른지 확인해주세요

2023-06-07 15:15 UTC, Ji-soo708 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    @DisplayName("OAuth 로그인을 진행한 이메일로 자체 회원가입을 한다")
회원가입이 가능한지 확인하는 코드이기 때문에 MemberServiceTest에 넣을지 고민을 했지만 Apple 로그인 관련 종속성이 AuthServiceTest에만 존재하기 때문에 AuthServiceTest에 테스트 코드를 작성했습니다. 좋은 의견이 있다면 코멘트 달아주세요.

2023-06-08 01:18 UTC, kth990303 requested changes
기능 동작 문제 없는거 확인했어요~ 쿼리 성능 관련해서 하나 코멘트 남겼으니 확인해주세요

2023-06-08 01:18 UTC, kth990303 commented on src/main/java/mocacong/server/repository/MemberRepository.java
> +
쓰이는 곳이 회원가입 시에 중복확인하는 경우밖에 없는 것 같아서, 아래 메서드도 괜찮을 것 같아요.

```suggestion
Boolean existsByPlatformAndEmail(Platform platform, String email);
```

Optional<Member> 반환형은 Member 속성의 모든 값을 가져오기 때문에 조금 더 부하가 클 듯 해요

2023-06-08 01:18 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +        memberRepository.findByEmailAndPlatform(memberSignUpRequest.getEmail(), platform)
여기서 Platform에 `MOCACONG`만 들어가니까 아예 파라미터로 안받고 `MOCACONG`으로 해도 괜찮을 듯하네요. 나중에 추가로 고쳐야되면 그 때 만들어도 괜찮을거같아요

2023-06-08 01:18 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +    private void validateDuplicateMember(Platform platform, MemberSignUpRequest memberSignUpRequest) {
모카콩 서비스 로직에서 `validateDuplicateNickname` 메서드랑 이 메서드의 닉네임 검증이랑 완전히 똑같은 역할을 하고 있었네요.. 지금 봤네요. validateDuplicateNickname를 사용하게 바꿔도 좋을듯해요

2023-06-08 01:18 UTC, kth990303 commented on src/main/java/mocacong/server/domain/Member.java
> +})
좋습니다. 개발서버에서 아래 두 쿼리 모두 테스트해봤는데, email, platform 순서가 어떻든 간에 거의 비슷한 성능을 나타내서 지금 constraint 순서 괜찮은거같아요.

```sql
explain select * from member where platform='MOCACONG' and email='kth990303@naver.co';
```

```sql
explain select * from member where email='kth990303@naver.co' and platform='MOCACONG';
```

<img width="942" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/cce6dde5-4c6c-4157-9d8b-676f49f34b06">

2023-06-08 01:18 UTC, kth990303 commented on src/test/java/mocacong/server/service/AuthServiceTest.java
> +    @DisplayName("OAuth 로그인을 진행한 이메일로 자체 회원가입을 한다")
네 지금 방법 좋다고 생각합니다. oauth 회원가입이 타 플랫폼 동일 이메일일 때에 에러를 반환하지 않는 것 테스트만 하면 충분하다고 생각하기 때문이에요.

사실 `assertDoesNotThrow`만으로도 충분하다고 생각했는데 꼼꼼히 잘해주셨네요

2023-06-08 05:24 UTC, Ji-soo708 commented on src/main/java/mocacong/server/repository/MemberRepository.java
> +
좋습니다~

2023-06-08 05:29 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/MemberService.java
> +        memberRepository.findByEmailAndPlatform(memberSignUpRequest.getEmail(), platform)
현재 상황에서는 `findByEmailAndPlatform` 이 자체 회원가입 기능에서만 쓰여서 platform 변수를 빼도 좋을 거 같네요.

2023-06-08 05:33 UTC, Ji-soo708 commented on src/main/java/mocacong/server/service/MemberService.java
> +    private void validateDuplicateMember(Platform platform, MemberSignUpRequest memberSignUpRequest) {
그러네요.. 바로 밑에 있는 코드였는데 알아채지 못했네요,,🥲

2023-06-08 06:13 UTC, kth990303 approved these changes
쿼리 관련해서 코멘트 하나 남겼어요.
approve 하겠습니다~

2023-06-08 06:13 UTC, kth990303 commented on src/main/java/mocacong/server/service/MemberService.java
> +        validateDuplicateNickname(memberSignUpRequest.getNickname());
닉네임도 Boolean exists 쿼리로 검증하면 더 좋지 않을까 싶어요.
<img width="1405" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/1dc1c2d7-5e21-435e-a627-e279073d7630">


<img width="1415" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/57135043/190c78e8-c957-4bc4-a8b8-90fb5308d242">

2023-06-08 07:23 UTC, merged